Wrapper generator improvments
krzema12/github-actions-kotlin-dsl pull request #102
Opened 2022-02-23 14:15 UTC by jmfayard

Improvments made in the wrapper-generator for PR https://github.com/krzema12/github-actions-kotlin-dsl/pull/101
without the changes to the wrapper requests

2022-02-23 18:56 UTC, krzema12 requested changes
Thanks for dividing changes into such small, easy to review commits :) Much appreciated, it was a pleasure to review.

2022-02-23 18:56 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
> +        |./gradlew ktlintFormat
It would be cool to run it automatically... But having this reminder is a good first step :)

2022-02-23 18:56 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
> +        wrappersToGenerate.groupBy { it.actionCoords.actionYmlUrl }
It's a valid case to generate wrappers for the same action but different versions. So we'd like to look only at the (owner, name) pair.

Side thing: `it.actionCoords.actionYmlUrl` hasn't been defined here yet. I think something got wrong with the order of commits.

2022-02-23 18:56 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/TextTransformation.kt
> +    val hasOnlyUppercases = none { it in 'a'..'z' }
I propose a simpler solution: call `.map { it.lowercase() }` in `toPascalCase`, after splitting. Then, `toCamelCase()` remains unchanged.

2022-02-23 18:56 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Generation.kt
> +fun suggestAdditionalTypings(actionCoords: ActionCoords, metadata: Metadata, existingTypings: Set<String>) {
Nice idea with the suggestions! :)

nit: let's move suggestions to a dedicated file, like you did with the tests: `TypingSuggestions.kt`.

2022-02-23 18:56 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Generation.kt
> +fun Metadata.linkedMapOfInputs(inputTypings: Map<String, Typing>): CodeBlock {
nit: let's make it a private function,

2022-02-23 18:56 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/GenerationTest.kt
> +        actionManifest.linkedMapOfInputs(emptyMap()).toString() shouldBe "return java.util.LinkedHashMap<String, String>()"
Let's assert on the whole output, as other tests do here. Goals: ensure how empty inputs affect the whole wrapper, not just one piece, and to not test some private function (not tested if it's actually called).

2022-02-23 18:56 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/metadata/MetadataReading.kt
> +val ActionCoords.actionYmlNoVUrl: String get() = "https://raw.githubusercontent.com/$owner/$name/${version.removePrefix("v")}/action.yml"
If we want to be precise, there should be also `actionYamlNoVUrl` :speak_no_evil:

2022-02-23 19:40 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
> +        |./gradlew ktlintFormat
Now done automatically :)

2022-02-23 19:41 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
> +        wrappersToGenerate.groupBy { it.actionCoords.actionYmlUrl }
`val ActionCoords.actionYamlUrl: String get() = "https://raw.githubusercontent.com/$owner/$name/$version/action.yaml"`

It contains the version so you can have two wrappers with a different version, not an issue

2022-02-23 19:57 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/TextTransformation.kt
> +    val hasOnlyUppercases = none { it in 'a'..'z' }
That converts `jdkFile` to `jdkfile` in `SetupJavaV2` which is a breaking change

2022-02-23 20:04 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/TextTransformation.kt
> +    val hasOnlyUppercases = none { it in 'a'..'z' }
True, we don't have this case covered in the unit tests, that's why I thought it works - got green tests :)
Anyway, before this change `toCamelCase` was a simple transformation over the output of `toPascalCase` - how about leaving it this way, and adjusting `toPascalCase` instead, so that the core complexity stays in one of these functions?

2022-02-23 20:05 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
> +        wrappersToGenerate.groupBy { it.actionCoords.actionYmlUrl }
Right, sorry! I misread something.

2022-02-23 20:12 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/TextTransformation.kt
> +    val hasOnlyUppercases = none { it in 'a'..'z' }
I modified `toPascalCase()` but in a conversative manner (only if all in caps lock) to avoid side effects

2022-02-23 20:12 UTC, jmfayard commented
I think I'm done

2022-02-24 07:12 UTC, krzema12 requested changes
The changes look good, thanks! Just one more last step: cleanup of git history. Please:
* remove multiple `Regenerate wrappers` - in fact you can rewrite the history to remove all of them because the workflow will add a new one
* make the history linear, there are two unnecessary merge commits:
![image](https://user-images.githubusercontent.com/3110813/155475851-06d95d95-e513-4d59-a705-4cd4a823d50c.png)

2022-02-24 09:36 UTC, krzema12 commented
These changes are merged, I just cleaned up the history a bit. Thank you! :) :tada:

2022-02-24 09:36 UTC, closed without merging