Add wrapper requests for popular actions
krzema12/github-actions-kotlin-dsl pull request #103
Opened 2022-02-24 13:24 UTC by jmfayard

I added the definitions of all the requests but enabled only the first ten

2022-02-24 18:07 UTC, krzema12 requested changes

2022-02-24 18:07 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +            "push" to StringTyping, // nope, it's not a boolean
Why do we need these comments? I assume the explicit string typing is here so that the wrapper generator doesn't hint boolean, but it just does its job - IMO no need for the comments. We can make the generator fail in case some suggestion is not addressed (separate PR please).

2022-02-24 18:07 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +            "cache-write-only" to StringTyping, // could be boolean but breaking change
About explicit string typing, it should be actually done in the previous PR. Could you create a separate one that addresses such suggestions for existing wrappers?

2022-02-24 18:07 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +    WrapperRequest(ActionCoords("10up", "action-wordpress-plugin-deploy", "v2.0.0"),
Please let's have just 10 wrapper requests. As we agreed, the goal of batching by 10 is to make it easier for me to review both generated wrappers and wrapper requests.

2022-03-01 07:14 UTC, krzema12 requested changes

2022-03-01 07:14 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        mapOf()
If there are no custom typings, this argument can be omitted, and the whole wrapper request can be written in a single line for brevity. Same for Borales/actions-yarn.

2022-03-01 07:14 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        mapOf(
`"silent" to BooleanTyping` is missing: https://github.com/JamesIves/github-pages-deploy-action/blob/debb905d4035364918bed34dd3489c7a354be7a0/action.yml#L83

2022-03-01 07:14 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        mapOf(
`"update_existing" to BooleanTyping` is missing: https://github.com/JasonEtco/create-an-issue/blob/c796bdce77b0eebb39e2f4cb359893d764d4aa91/README.md?plain=1#L97

2022-03-01 07:14 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        mapOf(
`"security" to EnumTyping("Security", listOf("strict", "loose"))` missing, see https://github.com/SamKirkland/FTP-Deploy-Action/blob/d0aa83872616587eb552bc831bb9166b3f9c5ad5/action.yml#L43

2022-03-01 07:14 UTC, krzema12 commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/azure/LoginV1.kt
> +        public object Azureusgovernment : LoginV1.Environment("azureusgovernment")
I'm wondering if we could make the generator accept the object name, so instead of `Azureusgovernment` it could produce something custom like `AsureUSGovernment`. Would look nicer right?

2022-03-01 10:25 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +            "status" to EnumTyping("Status", listOf("success", "failure", "cancelled")),
Yep but the `Custom` enum clashed with the `Custom` class

2022-03-01 12:08 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +            "status" to EnumTyping("Status", listOf("success", "failure", "cancelled")),
Oh, that's an interesting case. Ok, for now let's have the users write `Custom("custom")`.

2022-03-02 09:49 UTC, merged