write multiple workflows from single script
krzema12/github-actions-kotlin-dsl pull request #105
Opened 2022-02-27 16:21 UTC by NikkyAI

2022-02-28 06:32 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/WriteWorkflows.kt
> +fun writeWorkflows(
I have troubles understanding the use case for this function. There's already `Workflow.writeToFile()`. If you want to write more than one, you can just iterate over them. `args` lets you just write a single workflow, but you can just choose the workflow you want. Is your goal having a single script (entry point) for generating all or chosen workflow? If yes, why can't the script write all workflows every time?

2022-03-01 01:08 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/WriteWorkflows.kt
> +fun writeWorkflows(
The function writes all of them at once to file when invoked without args, the goal is to also have working consistency checks for all the generated workflows

2022-03-01 01:10 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/WriteWorkflows.kt
> +fun writeWorkflows(
Using args is mainly for the consistency checks.. The user does not have to redirect the output into file anymore.. We can add more sanity checks.. Eg. Check that working for is in the root of the repo.

2022-03-01 01:12 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/WriteWorkflows.kt
> +fun writeWorkflows(
If nothing else, i hope that the utilities i wrote for the tests helps in improving the rest of the code :P

2022-03-01 06:37 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/WriteWorkflows.kt
> +fun writeWorkflows(
Ok, I get your point. The problem here is that nearly everyone using this library has its ideas on how to write the workflows to files :sweat_smile: I'm a bit reluctant to adding support for all of them in the library (already added one in https://github.com/krzema12/github-actions-kotlin-dsl/commit/10ed9642c362beeb73b612d7d99bed430dd4b998) because the public APIs cost, they add complexity and need to be tested and maintained. Instead I aim at providing some basic APIs, and you can then have a function like the one here to implement your approach (from what I see, your function uses library's already available public API right?). Once the library has some more users, I'm eager to analyze how they do the workflows writing, and then maybe some popular option will emerge for which it makes sense to add utilities/support in the library itself.

As a low-hanging fruit, what we could do that could help you is adding `addConsistencyCheck: Boolean` to
https://github.com/krzema12/github-actions-kotlin-dsl/blob/51a9780e1f4e265755a456a87b9718d74802f7d2/library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt#L56
which would simplify your function a bit. It's a cheap change within already existing API.

2022-03-01 06:37 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> -                "diff -u '${targetFile.pathString.replace('\\', '/')}' " +
Wow, I didn't know about `invariantSeparatorsPathString`, thanks! :) I'll make this change alone.

2022-03-01 12:26 UTC, NikkyAI commented
My function needs the consistency check on he yaml to pass some kind of id/name 
The rest can be done in the scripts if we need to, or i can be in a extension library maybe

2022-03-02 06:24 UTC, krzema12 commented
> My function needs the consistency check on he yaml to pass some kind of id/name if that could be modified or be passed on as a lambda.. The rest can be done in the scripts if we need to, or it can be in a extension library maybe

This id/name would be there to run generation for a chosen workflow. What if your function would regenerate all workflows every time? What problem would it create? I think the performance is not an issue given that writing a single workflow is not computationally or IO expensive.

2022-03-02 12:30 UTC, NikkyAI commented
looking at how the selfcheck works..
```bash
"diff -u '.github/workflows/someworkflow.yaml' <('someScript.main.kts')
```

it relies on the stout output of the script to diff against

i just tried to stay compatible how (presumably) people use the library so far.. (because thats how the README explains the setup)


we could copy the original file, regenerate and compare them too
but that might cause weird issues or github being unhappy about the workflow modifying itself ?

2022-03-02 13:48 UTC, krzema12 commented
Sorry, let's go back to my questions, otherwise I don't understand the original problem.

To visualize it, the proposed approach is to have:

```kotlin
            writeWorkflows(
                addConsistencyCheck = true,
                workflows = listOf(
                    workflow1,
                    workflow2
                ),
                "Test workflow 1",
            )
```

I propose writing
```kotlin
listOf(
    workflow1,
    workflow2,
).forEach {
    it.writeToFile(addConsistencyCheck = true)
}
```

(we'd need to add `addConsistencyCheck` to `writeToFile`, but we can do it). **Would that work for you?**

2022-03-02 14:12 UTC, NikkyAI commented
without generating individual to stdout how do we do consistency checks ?

if the yaml can still do a diff of itself against some output or generated file from the script then that works

2022-03-02 14:59 UTC, jmfayard commented
If the parameter`fun Workflow.writeToFile(addConsistencyCheck: Boolean = false)` can be added, that's all I ned.
The code says it can't be done currently, and I don't know what would need to be changed for that.

https://github.com/krzema12/github-actions-kotlin-dsl/blob/b8f252e4816b85cdb29c70a6561660b8c7f3d567/library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt#L56-L62

2022-03-02 16:06 UTC, NikkyAI commented
we could replace the check with a step running the script and then
```bash
git diff .github/workflows/workflowname.yaml | wc -l
```
as a empty output is 0 lines == no error

otherwise this works too

```bash
test $(git diff .github/workflows/workflowname.yaml | wc -l) -eq 0
```

2022-03-02 18:11 UTC, krzema12 commented
@NikkyAI I like this approach! We could add `addConsistencyCheck` argument to `writeToFile` that would use this approach. About support for other platforms, I don't think we have to bother since we can run the consistency check job on UbuntuLatest.

2022-03-04 07:58 UTC, krzema12 requested changes

2022-03-04 07:58 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +                "test \$(git diff '${targetFile.invariantSeparatorsPathString}' | wc -l) -eq 0"
We want to support the previous consistency check logic in `toYaml`. The `git diff`-based one should be used only if using `writeToFile(true)`. Otherwise it's a breaking change and we force everyone to use the new method.

2022-03-04 07:58 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +            run("Execute script", sourceFile.invariantSeparatorsPathString)
Would be good to remove the target file first. Otherwise there's a risk someone didn't actually call `writeToFile()` in the script, the script won't modify the target file so `git diff` will produce empty diff, and the consistency check will succeed where it shouldn't.

2022-03-04 07:58 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/WriteWorkflows.kt
> +fun writeWorkflowsOrPrintYaml(
I thought we agreed to not add this function. Is it some leftover?

2022-03-04 07:58 UTC, krzema12 commented on README.md
> -4. Generate the YAML by calling the above script and redirecting its output to the desired YAML file path:
This guide should differentiate between both ways, e.g. removing `> .github/workflows/hello_world_workflow.yml` in case of using the stdout redirection is incorrect.

2022-03-04 07:58 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/EndToEndTest.kt
> +        workflowWithTempTargetFile.writeToFile(addConsistencyCheck = false)
Please also add tests for `writeToFile(addConsistencyCheck = true)`.

2022-03-04 10:02 UTC, NikkyAI commented on library/src/test/kotlin/it/krzeminski/githubactions/EndToEndTest.kt
> +        workflowWithTempTargetFile.writeToFile(addConsistencyCheck = false)
added a test for it

2022-03-04 10:03 UTC, NikkyAI commented on README.md
> -4. Generate the YAML by calling the above script and redirecting its output to the desired YAML file path:
i reverted my changes to the gide, only adjusting the section about `writeToFIle()` a bit, removing the note about not providing consistency checks

2022-03-04 10:04 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/WriteWorkflows.kt
> +fun writeWorkflowsOrPrintYaml(
i removed it

2022-03-04 10:05 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +            run("Execute script", sourceFile.invariantSeparatorsPathString)
good idea, i will do that

2022-03-04 10:11 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +                "test \$(git diff '${targetFile.invariantSeparatorsPathString}' | wc -l) -eq 0"
sensible, i have made the required changes

2022-03-04 19:07 UTC, krzema12 requested changes

2022-03-04 19:07 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +                    "test \$(git diff '${targetFile.invariantSeparatorsPathString}' | wc -l) -eq 0"
How about simplifying it to
```suggestion
                    "git diff --exit-code '${targetFile.invariantSeparatorsPathString}'"
```

https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---exit-code

2022-03-05 09:41 UTC, NikkyAI commented on library/src/test/kotlin/it/krzeminski/githubactions/FixNewlines.kt
> +fun String.fixNewlines(): String {
would `unixNewlines()` work better?
the goal is to replace `/r/n` from windows files with `/n` so that we can compare the text

2022-03-05 09:45 UTC, NikkyAI commented on library/src/test/kotlin/it/krzeminski/githubactions/FixNewlines.kt
> +fun String.fixNewlines(): String {
no clue how it worked before.. when i tested this locally on windows it failed.. (since then i worked on linux), i will have to switch to windows again and see again

2022-03-05 10:00 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +                    "test \$(git diff '${targetFile.invariantSeparatorsPathString}' | wc -l) -eq 0"
i completely overlooked that, good find

2022-03-05 10:01 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +fun Workflow.toYaml(addConsistencyCheck: Boolean = true, useGitDiff: Boolean = false): String {
sensible, i did that

2022-03-05 10:01 UTC, NikkyAI commented on library/src/test/kotlin/it/krzeminski/githubactions/EndToEndTest.kt
> +        // when
i made a new test for it

2022-03-05 14:15 UTC, NikkyAI commented on library/src/test/kotlin/it/krzeminski/githubactions/FixNewlines.kt
> +fun String.fixNewlines(): String {
well.. i dunno why but it works without just fine.. and since its not necessary.. removed it again

2022-03-05 17:31 UTC, krzema12 requested changes
Minor ones.

2022-03-05 17:31 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Workflow.kt
> +package it.krzeminski.githubactions.domain
Let's avoid making whitespace changes. Here I think line endings changed?

2022-03-05 17:31 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/EndToEndTest.kt
> +    test("writeToFile() - write multiple workflows") {
Hmm, just wondering: what added value does this test have? It just calls writeToFile twice.

2022-03-05 17:32 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Workflow.kt
> +package it.krzeminski.githubactions.domain
In The tests file as well.

2022-03-05 17:33 UTC, NikkyAI commented on library/src/test/kotlin/it/krzeminski/githubactions/EndToEndTest.kt
> +    test("writeToFile() - write multiple workflows") {
honestly, it was a different function before.. might as well remove it

2022-03-06 05:08 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Workflow.kt
> +package it.krzeminski.githubactions.domain
#115

2022-03-07 08:08 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Workflow.kt
> +package it.krzeminski.githubactions.domain
i might have had my git misconfigured, it had `core.autocrlf` enabled in linux.. which messed some stuff up
not sure if i fixed that before or after i cloned that..

2022-03-07 08:15 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Workflow.kt
> +package it.krzeminski.githubactions.domain
should be fixed again

2022-03-07 10:52 UTC, krzema12 commented
Looks good code-wise! One last thing to ensure: did you test it end-to-end, running on GitHub?

2022-03-07 13:27 UTC, krzema12 commented
> Looks good code-wise! One last thing to ensure: did you test it end-to-end, running on GitHub?

BTW, having true end-to-end tests is in scope of https://github.com/krzema12/github-actions-kotlin-dsl/issues/87. The current EndToEndTest.kt is a misnomer, it's rather about integration testing.

2022-03-07 14:21 UTC, NikkyAI commented
i did not go though the effort to setup a repo for my fork to do a proper end-to-end test
but i guess i could verify that it "breaks"  verifying a older scripts, i shall do that

2022-03-07 14:33 UTC, NikkyAI commented
testing around a bit the error modes i managed to reproduce are..

1. file missing

```
Run git diff --exit-code '.github/workflows/docker_workflow.yml'
fatal: ambiguous argument '.github/workflows/docker_workflow.yml': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Error: Process completed with exit code 128.
```

2. file content differs
```diff
git diff --exit-code '.github/workflows/docker_workflow.yml'
diff --git a/.github/workflows/docker_workflow.yml b/.github/workflows/docker_workflow.yml
index 10c2366..c6fbb0b 100644
--- a/.github/workflows/docker_workflow.yml
+++ b/.github/workflows/docker_workflow.yml
@@ -13,25 +13,8 @@ on:
       - 'main'
 
 jobs:
-  "check_yaml_consistency":
-    runs-on: "ubuntu-latest"
-    steps:
-      - id: step-0
-        name: Check out
-        uses: actions/checkout@v2
-      - id: step-1
-        name: Install Kotlin
-        run: sudo snap install --classic kotlin
-      - id: step-2
-        name: execute script
-        run: rm '.github/workflows/docker_workflow.yml' && '.github/workflows/docker_workflow.main.kts'
-      - id: step-3
-        name: Consistency check
-        run: git diff --exit-code '.github/workflows/docker_workflow.yml'
   "build_job":
     runs-on: "ubuntu-latest"
-    needs:
-      - "check_yaml_consistency"
...
...
...
```

so far it works, ofc i cannot make it "work" without the new code hosted somewhere for the script to use
maybe i will try to figure out how to make jitpack with work kotlin scripts later..

2022-03-07 16:19 UTC, krzema12 commented
Its enough for me, thanks :) I'll take care of merging it properly tomorrow. Thank you for the contribution! 🎉

2022-03-07 19:21 UTC, krzema12 approved these changes

2022-03-07 19:22 UTC, krzema12 commented
@NikkyAI there are some conflicts - could you resolve them please?

2022-03-07 21:07 UTC, NikkyAI commented
> @NikkyAI there are some conflicts - could you resolve them please?

i see no conflicts ?

2022-03-08 07:51 UTC, krzema12 commented
Merged manually.

2022-03-08 07:51 UTC, closed without merging