[#95] Add wrappers for popular actions - batch 2
krzema12/github-actions-kotlin-dsl pull request #112
Opened 2022-03-05 09:52 UTC by jmfayard

11 more actions from https://pastebin.com/k5f0eJaJ

2022-03-05 09:53 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +                "login", "owner", "package", "publish", "yank")
https://doc.rust-lang.org/cargo/commands/index.html

2022-03-08 08:30 UTC, krzema12 requested changes

2022-03-08 08:30 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
> -        println("Generating ${actionCoords.owner}/${actionCoords.name}@${actionCoords.version}...")
Why this change? It also doesn't fit this PR, it seems unrelated.

2022-03-08 08:30 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("actions", "labeler", "v3"),
There's already [v4](https://github.com/actions/labeler/releases/tag/v4):
```suggestion
        ActionCoords("actions", "labeler", "v4"),
```

2022-03-08 08:30 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("actions", "setup-dotnet", "v1"),
There's already [v2](https://github.com/actions/setup-dotnet/releases/tag/v2):
```suggestion
        ActionCoords("actions", "setup-dotnet", "v2"),
```

2022-03-08 08:30 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("actions", "setup-go", "v2"),
There's already [v3](https://github.com/actions/setup-go/releases/tag/v3):

```suggestion
        ActionCoords("actions", "setup-go", "v3"),
```

2022-03-08 08:30 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +            "stable" to BooleanTyping,
Not present in v3.

2022-03-08 08:30 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("actions", "stale", "v4"),
There's already [v5](https://github.com/actions/stale/releases/tag/v5):

```suggestion
        ActionCoords("actions", "stale", "v5"),
```

2022-03-08 08:30 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +            "days-before-close" to IntegerTyping,
For all inputs expressed in days, -1 is a special value denoting never/infinity. It would be good to express them as `IntegerWithSpecialValueTyping` with `Never` special value.

2022-03-08 08:49 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
> -        println("Generating ${actionCoords.owner}/${actionCoords.name}@${actionCoords.version}...")
The println statement is done elsewhere, I've simply added the URL to the YAML file, which is helpful/necessary to find out what typing should be added

```
Generating ActionCoords("actions", "setup-go", "v3") from https://raw.githubusercontent.com/actions/setup-go/v3/action.yml
Generating ActionCoords("actions", "stale", "v5") from https://raw.githubusercontent.com/actions/stale/v5/action.yml
Generating ActionCoords("actions-rs", "audit-check", "v1") from https://raw.githubusercontent.com/actions-rs/audit-check/v1/action.yml
```

2022-03-08 08:52 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
> -        println("Generating ${actionCoords.owner}/${actionCoords.name}@${actionCoords.version}...")
Ok, got it. Could you place it in a dedicated commit (to not mix it with adding new wrappers) and leave printing `actions/setup-go@v3` instead of a Kotlin snippet?

2022-03-08 09:00 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("actions", "labeler", "v3"),
done

2022-03-08 09:00 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("actions", "setup-go", "v2"),
done

2022-03-08 09:01 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +            "days-before-close" to IntegerTyping,
Done.
I was worried that the generator produces 3 classes names "Days" clashing with each other, but it worked out of the box 👍

2022-03-08 09:01 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +            "stable" to BooleanTyping,
done

2022-03-08 10:05 UTC, merged