[#110] Add @Deprecated to wrappers for actions of older versions
krzema12/github-actions-kotlin-dsl pull request #113
Opened 2022-03-05 10:24 UTC by jmfayard

See https://github.com/krzema12/github-actions-kotlin-dsl/issues/110

2022-03-08 08:59 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/domain/ActionCoords.kt
> +    val deprecatedByVersion: String? = null
Ok, so you propose to mark it manually for each wrapper? I'm wondering if it will be maintainable. Imagine

```
WrapperRequest(ActionCoords("foo", "bar", "v2", deprecatedByVersion = "v3"))
WrapperRequest(ActionCoords("foo", "bar", "v3"))
```

then another version comes and we need to update two previous requests:
```
WrapperRequest(ActionCoords("foo", "bar", "v2", deprecatedByVersion = "v4"))
WrapperRequest(ActionCoords("foo", "bar", "v3", deprecatedByVersion = "v4"))
WrapperRequest(ActionCoords("foo", "bar", "v4"))
```

Pro: fine-grained control over deprecation. Con: a possibility to make a mistake, and having to manually change it. I was thinking of having some automatic way of inferring deprecation, e.g. we specify a list of versions for wrapper requests and only the latest one is not marked as deprecated. I'm also wondering if it's a valid case that some non-latest version is still not deprecated, e.g. the action maintainers maintain more than one major version at a time. Any thoughts?

2022-03-08 09:40 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/domain/ActionCoords.kt
> +    val deprecatedByVersion: String? = null
@krzema12 

I would retain fine-grained control over deprecation.

It doesn't seem so much work, and beside we can automate suggestions like we do for typing.

```
warning: newer version available for ActionCoords("foo", "bar", "v3"). Maybe add: deprecatedByVersion = "v4" ?
```

2022-03-08 09:53 UTC, krzema12 requested changes

2022-03-08 09:53 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Generation.kt
> +    val newerClass = coords.copy(version = coords.deprecatedByVersion ?: return this)
I propose to make it clear when this function is a no-op (I know, it's longer, but I found it pretty confusing to find this `return this` inside the parenthesis. Shorter is not always more readable :sweat_smile:):
```suggestion
    if (coords.deprecatedByVersion == null) {
        return this
    }

    val newerClass = coords.copy(version = coords.deprecatedByVersion)
```

2022-03-08 09:53 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/domain/ActionCoords.kt
> +    val deprecatedByVersion: String? = null
Ok, let's refrain from automating for now :)

2022-03-08 10:42 UTC, jmfayard commented
I now automatically suggest deprecations @krzema12

2022-03-08 12:33 UTC, krzema12 requested changes

2022-03-08 12:33 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/GenerationEntryPoint.kt
> +fun List<WrapperRequest>.suggestDeprecations(): String {
Nicely fits a separate file, like in case of typing suggestions. Here: `DeprecationSuggestions.kt`.

2022-03-08 12:33 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/VersionSuggestionsTest.kt
> +class VersionSuggestionsTest : FunSpec({
Once the new logic reaches the new file:
```suggestion
class DeprecationSuggestionsTest : FunSpec({
```

2022-03-08 12:33 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/VersionSuggestionsTest.kt
> +    test("Suggest deprecation") {
Please also cover a case where `deprecatedByVersion` doesn't point to the newest version - it should also produce a warning right?

2022-03-08 12:33 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/GenerationTest.kt
> +        val coords = ActionCoords("john-smith", "action-with-no-inputs", "v2", deprecatedByVersion = "v3")
Let's use action's name that corresponds to test's subject, e.g. here
```suggestion
        val coords = ActionCoords("john-smith", "deprecated-action "v2", deprecatedByVersion = "v3")
```
and also see the target file name.

2022-03-09 06:36 UTC, krzema12 requested changes

2022-03-09 06:36 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/wrappersfromunittests/ActionWithNoInputsV2.kt
> +public class ActionWithNoInputsV2() : Action("john-smith", "action-with-no-inputs", "v2") {
I think you forgot to remove this file after renaming it.

2022-03-09 06:36 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Generation.kt
> +            .addMember("message = %S", "This action has a newer major version")
Could we mention the new version here in the warning?
```suggestion
            .addMember("message = %S", "This action has a newer major version: ${coords.deprecatedByVersion}")
```

2022-03-09 06:36 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
> +@file:Suppress("DEPRECATION")
Instead of adding these suppressions, we could first use `CheckoutV3` in all tests.

2022-03-09 06:43 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
> +@file:Suppress("DEPRECATION")
https://github.com/krzema12/github-actions-kotlin-dsl/commit/8c987101e3560b25ee60c9fc783c74d7680cc93b

2022-03-09 07:17 UTC, jmfayard commented on library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
> +@file:Suppress("DEPRECATION")
Thanks :)

2022-03-09 07:18 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/wrappersfromunittests/ActionWithNoInputsV2.kt
> +public class ActionWithNoInputsV2() : Action("john-smith", "action-with-no-inputs", "v2") {
deleted

2022-03-09 07:18 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Generation.kt
> +            .addMember("message = %S", "This action has a newer major version")
Done - I used the name of the class instead of just the version

2022-03-09 18:11 UTC, krzema12 requested changes

2022-03-09 18:11 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +@file:Suppress("DEPRECATION")
Are these still needed? See also other files with suppression added.

2022-03-09 19:09 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +@file:Suppress("DEPRECATION")
@krzema12 I removed this one and two others

2022-03-09 20:11 UTC, krzema12 requested changes

2022-03-09 20:11 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/DeprecationSuggestions.kt
> +                    """WARNING: ActionCoords("owner", "other-name", "v3") is deprecatedByVersion "v2", an older version ?"""
The values are hard-coded just to make the unit test pass :see_no_evil:  :thinking: :smile:

2022-03-09 20:19 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/DeprecationSuggestions.kt
> +                    """WARNING: ActionCoords("owner", "other-name", "v3") is deprecatedByVersion "v2", an older version ?"""
TDD best practice 😊 

Fixed

2022-03-09 20:47 UTC, krzema12 approved these changes

2022-03-09 20:48 UTC, merged

2022-03-09 20:48 UTC, krzema12 commented
Thank you! :tada: