MissingAction for when no wrapper is available
krzema12/github-actions-kotlin-dsl pull request #133
Opened 2022-03-16 13:15 UTC by jmfayard

What?

Add a type-unsafe subclass of action

Why?

If a wrapper is missing, 
- either you use the wrapper-generator to produce a complete type safe wrapper,
- or you use this Missing Action where you pass only the arguments you need as a type-unsafe map.
- there isn't a real point in creating your own half assed wrapper manually

2022-03-16 18:11 UTC, krzema12 requested changes
Given this new approach of using any action, let's also update the docs here:

2022-03-16 18:11 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/MissingAction.kt
> + * Used by the script generator when no Action Wrapper can be found
This comment can be made more generic - the class can be used not only by the generator, but every time there's no wrapper and a quick untyped wrapper is needed.

2022-03-16 18:11 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/MissingAction.kt
> +class MissingAction(
How about
```suggestion
class CustomAction(
```
? MissingAction looks a bit as a placeholder, and it may confuse the user whether such action invocation will actually work or not.

2022-03-16 18:11 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/MissingAction.kt
> +    val with: Map<String, String>,
```suggestion
    val inputs: Map<String, String>,
```
? `with` suggests that also non-input parameters can be passed here. I know `wirh` is in line with GitHub API, however we're going to have `_customInputs` or `_freeInputs` in all generated wrappers, where `_customWith` would look weird :smile:

2022-03-16 18:11 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/yaml/StepsToYamlTest.kt
> +            ExternalActionStep(
Instead of piggy-backing on existing simple test case, I propose to add a new test under `describe("command step")`.

2022-03-16 19:27 UTC, jmfayard commented
Done. 
Please verify what I've done with `ActionWithOutputs`, I'm not familiar with it.

2022-03-17 08:08 UTC, krzema12 requested changes

2022-03-17 08:08 UTC, krzema12 commented on docs/user-guide/using-actions.md
> +you can use a [`CustomAction`](https://github.com/krzema12/github-actions-kotlin-dsl/blob/main/library/src/main/kotlin/it/krzeminski/githubactions/actions/CustomAction.kt)
I realized that we may want to keep both ways of custom wrappers documented. The one with inheriting from `Action`/`ActionWithOutputs` has its advantage: being able to type the inputs and have fields for outputs, while using `CustomAction` using it is unsafe because it relies solely on strings.

I propose adding two subsections to "User-defined actions" section, e.g. "Type-safe" (leaving its contents as it was) and "Unsafe" (newly added `CustomAction`).

I realize I may be nitpicky here, so let me know if you want me to take care of these docs.

2022-03-17 08:08 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/yaml/StepsToYamlTest.kt
> +        val outputs = customAction.buildOutputObject("someStepId")
This test file is only about `stepsToYaml()` - testing some logic of `CustomAction` should go to `CustomActionTest.kt`.

2022-03-17 08:08 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/CustomAction.kt
> + * Consider contributing a proper wrapper to the library, see [WrappersToGenerate.kt]
This KDoc reference doesn't work, let's just skip it
```suggestion
 * Consider contributing a proper wrapper to the library, see WrappersToGenerate.kt in wrapper-generator module.
```

2022-03-17 08:08 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/yaml/StepsToYamlTest.kt
> +                         |  uses: actions/checkout@v3
No need to change (BTW, interesting that the test still passes and the new line at the end doesn't matter here).

2022-03-17 09:07 UTC, jmfayard commented on docs/user-guide/using-actions.md
> +you can use a [`CustomAction`](https://github.com/krzema12/github-actions-kotlin-dsl/blob/main/library/src/main/kotlin/it/krzeminski/githubactions/actions/CustomAction.kt)
Yes that would be nice if you can do it :)

2022-03-17 09:07 UTC, jmfayard commented on library/src/test/kotlin/it/krzeminski/githubactions/yaml/StepsToYamlTest.kt
> +        val outputs = customAction.buildOutputObject("someStepId")
Done

2022-03-17 09:07 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/CustomAction.kt
> + * Consider contributing a proper wrapper to the library, see [WrappersToGenerate.kt]
Done

2022-03-17 09:08 UTC, jmfayard commented on library/src/test/kotlin/it/krzeminski/githubactions/yaml/StepsToYamlTest.kt
> +                         |  uses: actions/checkout@v3
Done

2022-03-17 09:31 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/actions/CustomActionTest.kt
> +        val yaml = steps.stepsToYaml()
We misunderstood each other - `stepsToYaml()` **should** be tested in `StepsToYamlTest` :smile: Just

```kotlin
val outputs = customAction.buildOutputObject("someStepId")
```

and related assertion should be moved here.

2022-03-17 12:02 UTC, krzema12 commented on docs/user-guide/using-actions.md
> +you have two ways go go.
```suggestion
you have two ways to proceed.
```

2022-03-17 12:07 UTC, krzema12 approved these changes

2022-03-17 12:08 UTC, merged