Add all remaining triggers
krzema12/github-actions-kotlin-dsl pull request #134
Opened 2022-03-16 13:46 UTC by jmfayard

Later need to add type-safe arguments for the remaining triggers, especially an enum for "types", but that will be backward compatible.

Change the way triggers are transformed to yaml, so that it can be used by the script-generator to transform to Kotlin

Add @Serializable so that it can be used later by the script-generator

2022-03-17 08:12 UTC, krzema12 commented
There are several things mixed in this PR, let's start with having a separate PR for adding the triggers, without adding serialization stuff or adjusting custom YAML serialization logic.

2022-03-17 09:10 UTC, jmfayard commented
No problem for removing the kotlinx.serialization stuff, 
but I would rather not implement YAML serialization for 30 new wrappers just to revert it later because there is a better way that works both for serialization do YAML *and* Kotlin :)

2022-03-17 09:20 UTC, jmfayard commented
kotlinx.serialization removed from library module

2022-03-22 17:07 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt
> +val triggerClassMap: List<Pair<String, KClass<*>>> = listOf(
Observation: this property becomes a part of public API, this library makes use of it by searching by values, and there's some reflection going on here (in case of missing entry in this map, the code will fail in runtime). To be honest, seems shady and a bit hacky :raised_eyebrow: :smile: Let's try to find a better solution.

My goal is to keep this library high-quality and maintainable, while side projects like YAML-to-Kotlin converter should have as little impact on the library as possible. By exposing such semi-public API to be used by the converter, the library extends its hand to the converter sacrificing its own quality. I'd rather go the other way: first implement all the triggers as if the converter wasn't there, and then find the best approach so that the converter can do its job. It's also more expected for the converter to use reflection because that code will be less often used, and acts like an addition to the library.

What comes to my mind as something satisfactory for the converter, and preserving the right level of quality here in the library: having YAML name defined in each trigger class. Then the converter could use reflection to get all subclasses of `Trigger` and find such class that has the expected YAML name. It would also mean no new piece of public API for this library, just some internal fields that the library uses internally, and the converter happens to know about them and access them by reflection.

WDYT? I hope you get my point, and we can work something out :muscle:

2022-03-22 17:08 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/JobsToYaml.kt
> +    if (_customArguments.isNotEmpty()) appendLine()
Is this change somehow related to adding the triggers?

2022-03-22 17:16 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/triggers/BranchProtectionRule.kt
> +data class BranchProtectionRule(
There at least two things mixed in this PR: adding all the triggers, and changing how they're serialized to YAML. The first part looks like something repetitive, a no-brainer that could go to a separate PR. This way we could simplify this PR. It's much easier for me to review several simpler PRs than a big one where several things are mixed - could you split it please? :pray:

Also, see my other PR where I suggest putting a YAML name for each trigger somewhere around class declaration. This way we may be able to satisfy both aspects at once.

2022-03-22 21:03 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt
> +val triggerClassMap: List<Pair<String, KClass<*>>> = listOf(
I fully understand the concern.

Can we declare a property inside `Trigger` to be implemented by each class? That would be enough for me.

Something like:

```kotlin
sealed class Trigger : HasCustomArguments {
    abstract val _triggerName: String
}

data class BranchProtectionRule(
    override val _customArguments: Map<String, CustomValue> = mapOf(),
) : Trigger() {
    override val _triggerName = "branch_protection_rule"
}
```

2022-03-22 21:06 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/JobsToYaml.kt
> +    if (_customArguments.isNotEmpty()) appendLine()
Yes, I had to remove an `append("\n")` in `ToYaml.kt` and reintroduce it here

2022-03-22 21:20 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt
> +val triggerClassMap: List<Pair<String, KClass<*>>> = listOf(
I fully agree with the concern.

In fact I had a look and I don't need it, I have suppresed it in a new commit

2022-03-22 21:25 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/triggers/BranchProtectionRule.kt
> +data class BranchProtectionRule(
The part that changes how they are serialized is simple:
It refactors this imperative call to `buildString()` here
https://github.com/krzema12/github-actions-kotlin-dsl/blob/9cd86cf9864ecad897c5c00d47fc79468564e92d/library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt#L27-L35

to a more functional style
https://github.com/krzema12/github-actions-kotlin-dsl/blob/5f1483c12de92b0609cd4032302e45eaaa59517d/library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt#L181-L188

called by this

https://github.com/krzema12/github-actions-kotlin-dsl/blob/5f1483c12de92b0609cd4032302e45eaaa59517d/library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt#L135-L141

The parts that don't fit this pattern are handled here:

https://github.com/krzema12/github-actions-kotlin-dsl/blob/5f1483c12de92b0609cd4032302e45eaaa59517d/library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt#L135-L141

The hardest part was where to add `\n` or remove it, see your comment on this.

2022-03-23 18:35 UTC, krzema12 requested changes
Looks good in general, some nitpicking.

2022-03-23 18:35 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt
> +        is Schedule -> emptyMap
Maybe `else -> emptyMap`?

2022-03-23 20:50 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt
> +        is Schedule -> emptyMap
Done

2022-03-23 20:50 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt
> +    is Push -> ""
Done

2022-03-23 20:55 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt
> +fun Trigger.triggerName() = when (this) {
@krzema12 I did using Kotlin's `@RequireOptIn` feature which is made for that
[feat: annotate as @InternalGithubActionsApi methods meant for the scr…](https://github.com/krzema12/github-actions-kotlin-dsl/pull/134/commits/dbca26975b47ba30911996fb915a9c4ddc94f66d)

2022-03-24 07:49 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/TriggersToYaml.kt
> +fun Trigger.triggerName() = when (this) {
Great idea! :)

2022-03-24 07:49 UTC, krzema12 approved these changes

2022-03-24 07:50 UTC, merged