Action._customArguments: Map<String, String>
krzema12/github-actions-kotlin-dsl pull request #137
Opened 2022-03-17 15:33 UTC by jmfayard

I've added `Action._customArguments: Map<String, String>`

I wonder if I should add `Action._actionVersion : String? = null`  that would override the default version as suggested in https://github.com/krzema12/github-actions-kotlin-dsl/issues/74

2022-03-17 15:37 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/GenerationTest.kt
> -                // This file was generated using 'wrapper-generator' module. Don't change it by hand, your changes will
I find super painful to have to cpopy/paste and then indent and escape the content of the file inside `GenerationTest.kt`

What I usually do instead is: 

- the current content of `DeprecatedActionV2.kt` is used as the expected value for the test
- the script writes the new content to `DeprecatedActionV2Actual.kt`
- if the content don't match, an assert is thrown and we simply have to compare `DeprecatedActionV2.kt` with `DeprecatedActionV2Actual.kt`, and update the changes that look good
- if the content do match, the test deletes the file `DeprecatedActionV2Actual.kt`

2022-03-17 20:37 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/GenerationTest.kt
> -                // This file was generated using 'wrapper-generator' module. Don't change it by hand, your changes will
Makes sense to me, we wouldn't have the same file in two places. Would you like to make such change in a separate PR, in existing tests?

2022-03-17 20:39 UTC, krzema12 commented
> I wonder if I should add a way to override the default version, as suggested in https://github.com/krzema12/github-actions-kotlin-dsl/issues/74

Would be cool (maybe `_overrideVersion`?), but it also deserves a separate PR :pray:

2022-03-17 20:43 UTC, krzema12 requested changes

2022-03-17 20:43 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/yaml/StepsToYamlTest.kt
> +    it("renders with action with custom arguments") {
The test itself looks good, but should be nested within `describe("external action step") {`.

2022-03-17 20:45 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/GenerationTest.kt
> -                // This file was generated using 'wrapper-generator' module. Don't change it by hand, your changes will
I see the whole contents of the expected files replaced, perhaps some whitespace changes? Let's make the refactoring you suggested first (having expected contents only in separate files), then this problem will disappear :magic

2022-03-17 21:58 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/GenerationTest.kt
> -                // This file was generated using 'wrapper-generator' module. Don't change it by hand, your changes will
https://github.com/krzema12/github-actions-kotlin-dsl/pull/140

2022-03-19 13:50 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/GenerationTest.kt
> -                // This file was generated using 'wrapper-generator' module. Don't change it by hand, your changes will
done

2022-03-19 13:50 UTC, jmfayard commented
@krzema12 I'm done, I integrated the changes from the main branch and rebased upon it

2022-03-21 07:44 UTC, krzema12 requested changes

2022-03-21 07:44 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Generation.kt
> +                    .addKdoc("Type-unsafe map where you can put any inputs that is not yet supported by the wrapper")
```suggestion
                    .addKdoc("Type-unsafe map where you can put any inputs that are not yet supported by the wrapper")
```

2022-03-21 07:44 UTC, krzema12 commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/googlegithubactions/SetupGcloudV0.kt
> +        public object AppEngineJava : SetupGcloudV0.Component("app-engine-java")
It's weird these changes appear here. Could you rebase on newest master again please?

2022-03-21 07:44 UTC, krzema12 commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/azure/DockerLoginV1.kt
> +    ).also {
Just got me thinking: why not simply
```kotlin
) + _customArguments
```
? Less imperative, more functional approach.

2022-03-21 07:44 UTC, krzema12 commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/azure/DockerLoginV1.kt
> +    public val _customArguments: Map<String, String> = mapOf()
I'm wondering if it should be a LinkedHashMap, consistently with what `toYamlArguments` returns. The reason for it is to have better control over the order of these in the resulting YAML, at the cost of having to write an extra `linked` in `linkedMapOf(...)`.

2022-03-21 08:12 UTC, jmfayard commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/azure/DockerLoginV1.kt
> +    ).also {
That would be of type `Map`, necessitating the whole expression to be wrapped a third time inside a `LinkedHashMap(...)`

2022-03-21 08:14 UTC, jmfayard commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/azure/DockerLoginV1.kt
> +    public val _customArguments: Map<String, String> = mapOf()
Actually `mapOf(...)` preserves the order exactly like `linkedMapOf(...)` plus it's inmutable contrary to the later

2022-03-21 09:47 UTC, jmfayard commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/azure/DockerLoginV1.kt
> +    ).also {
I have found a better solution

```kotlin
listOfNotNull(
   "foo-bar" to fooBar,
  *_customArguments.toList().toTypedArray(),
).toTypedArray()
```

2022-03-21 09:49 UTC, jmfayard commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/googlegithubactions/SetupGcloudV0.kt
> +        public object AppEngineJava : SetupGcloudV0.Component("app-engine-java")
I tried but it's my version that is correct:

```kotlin
EnumTyping("Component",
  listOf( "alpha","anthos-auth", "appctl",)
  ```

<img width="1112" alt="Action__customArguments__Map_String__String__by_jmfayard_·_Pull_Request__137_·_krzema12_github-actions-kotlin-dsl" src="https://user-images.githubusercontent.com/459464/159237769-4582c08d-0731-49ac-9f9a-0a8c9b143dc0.png">

Looks like the wrappers were not re-generated before committing

2022-03-22 07:45 UTC, krzema12 commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/googlegithubactions/SetupGcloudV0.kt
> +        public object AppEngineJava : SetupGcloudV0.Component("app-engine-java")
Oops, right. I fixed `main` branch added an extra check (https://github.com/krzema12/github-actions-kotlin-dsl/commit/c19510340d91ac070902583146916b872ff17cf9) so it shouldn't happen again.

2022-03-22 07:48 UTC, krzema12 commented
Looks good, but there's some noise related to cherry-picked changes. Could you please rebase on newest `main`?

2022-03-22 09:04 UTC, jmfayard commented
Done

2022-03-22 12:56 UTC, krzema12 requested changes
Just this one thing left, and we're merging :rocket:

2022-03-22 12:56 UTC, krzema12 commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/10up/ActionWordpressPluginDeployV2.kt
> +    public val _customArguments: Map<String, String> = mapOf()
Let's call it `_customInputs`, to stick to GitHub's nomenclature:
https://github.com/actions/checkout/blob/2d1c1198e79c30cca5c3957b1e3b65ce95b5356e/action.yml#L3

2022-03-22 13:59 UTC, jmfayard commented
Done

2022-03-22 14:05 UTC, krzema12 approved these changes
Thank you! :bow:

2022-03-22 14:07 UTC, merged