[Action wrapper request] google auth and setup-gcloud
krzema12/github-actions-kotlin-dsl pull request #138
Opened 2022-03-17 18:10 UTC by NikkyAI

i hope i did not miss anything, this is the first time adding wrappers

2022-03-17 20:07 UTC, krzema12 requested changes

2022-03-17 20:07 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("google-github-actions", "auth", "v0"),
This typing can be improved:

* `token_format` - enum
* `create_credentials_file` - boolean
* `access_token_scopes` - list of strings
* `id_token_include_email` - boolean

2022-03-17 20:07 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("google-github-actions", "setup-gcloud", "v0"),
Additionally:
* `cleanup_credentials` - boolean

2022-03-17 20:07 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +            "install_components" to ListOfTypings(","),
Did you consider a list of enums here? The components can be enumerated somehow: https://cloud.google.com/sdk/docs/components by calling `gcloud component list`.

2022-03-17 23:57 UTC, NikkyAI commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/10up/ActionWordpressPluginDeployV2.kt
> +) : ActionWithOutputs<ActionWordpressPluginDeployV2.Outputs>("10up",
i did not touch these files, this iwhat it generated, i will just revert the second commit

2022-03-18 00:20 UTC, NikkyAI commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +            "install_components" to ListOfTypings(","),
nice idea, i did that and added a comment for how to run the command to regenerate the list if it changes..

2022-03-18 00:29 UTC, NikkyAI commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("google-github-actions", "setup-gcloud", "v0"),
added

2022-03-18 00:29 UTC, NikkyAI commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("google-github-actions", "auth", "v0"),
added

2022-03-18 00:30 UTC, NikkyAI commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +            "credentials_json" to StringTyping,
its not needed, but it is te first parameter i added before even realizing it would generate more than the parameters specified..

2022-03-18 00:33 UTC, NikkyAI commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/10up/ActionWordpressPluginDeployV2.kt
> +) : ActionWithOutputs<ActionWordpressPluginDeployV2.Outputs>("10up",
i see why.. i ran the generator via main class in idea.. not via gradle command so it skipped the `ktlint format`

2022-03-18 19:32 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +                    // gcloud components list --format=json | jq -r '"\\"" + .[].id +"\","'
There's a typo in the command (at least it fails on my machine) + let's keep it sorted:
```suggestion
                    // To regenerate, run: gcloud components list --format=json | jq -r '"\"" + .[].id + "\","' | sort
```

2022-03-18 19:34 UTC, krzema12 requested changes
Looks good, just this one command fix + sorting and we're merging :smile:

2022-03-19 10:05 UTC, NikkyAI commented
i was sure there was some meaning to the order of components in the list that gcloud spits out, but sorted looks nicer

2022-03-19 11:24 UTC, krzema12 approved these changes

2022-03-19 11:24 UTC, krzema12 commented
Thanks! :)

2022-03-19 11:26 UTC, merged