tests: compare GeneratedFile.kt with GeneratedFileActual.kt
krzema12/github-actions-kotlin-dsl pull request #140
Opened 2022-03-17 21:57 UTC by jmfayard

When a generated file doesn't match what was expected,
the actual content is written to a file GeneratedFileActual.kt

Use IntelliJ's "Compare Files" Actions
and update GeneratedFile.kt if the change looks good

Next time the test run and match the expected content,
GeneratedFileActual.kt will be deleted

On GitHub Actions, fail instead of creating a new file

2022-03-18 20:38 UTC, krzema12 requested changes
Some nitpicking, but since I really don't like having surplus logic in the tests, let's try to simplify this function.

2022-03-18 20:38 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Utils.kt
> +            actualContent.replace(
Why is this replacement needed? It can be committed by accident, if someone copies the Actual file blindly.

2022-03-18 20:38 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Utils.kt
> +    if (System.getenv("GITHUB_ACTIONS") == "true") {
I'm wondering if we could simplify this function. One of the ideas is to behave the same way both on GitHub and locally. If we create this `Actual.kt` file on GH, it shouldn't hurt.

2022-03-18 20:38 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Utils.kt
> +        expectedFile.canRead() -> expectedFile.readText().removeWindowsNewLines()
Do we need to handle the `expectedFile.canRead() == false` case explicitly? It makes this method more complicated, and if it cannot be read, it should fail anyway. Assigning an empty string will make the issue harder to track down.

2022-03-18 22:43 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Utils.kt
> +            actualContent.replace(
You get a compilation error if  you have two classes with the same name in the same package.
That forces you to delete manually all `Actual` files every time you make a change.

>  It can be committed by accident, if someone copies the Actual file blindly.
I don't have a good answer for that

2022-03-18 22:45 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Utils.kt
> +        expectedFile.canRead() -> expectedFile.readText().removeWindowsNewLines()
`File.readText()` throws an exception when the file is not there.
That shouldn't happen IMHO, if you are adding a new test it should just create the `Actual` file and say that they differ

2022-03-18 22:48 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Utils.kt
> +    if (System.getenv("GITHUB_ACTIONS") == "true") {
On GitHub you want to fail if the content don't match, but you can't use IntelliJ after that to compare the expected and actual files. Hence `actualContent shouldBe expectedContent`

Doing that locally would log to the console the console of two files.
It's shorter and enough to have a message about which two files differ

2022-03-19 09:06 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Utils.kt
> +    if (System.getenv("GITHUB_ACTIONS") == "true") {
@krzema12 I added an assert that the expected file doesn't contain the actual package

2022-03-19 09:07 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/generation/Utils.kt
> +            actualContent.replace(
I've added an assert that the expected file doesn't contain the actual package

2022-03-19 11:28 UTC, krzema12 approved these changes

2022-03-19 11:30 UTC, merged