adds Job.timeoutMinutes, closes #141
krzema12/github-actions-kotlin-dsl pull request #143
Opened 2022-03-19 11:27 UTC by NikkyAI

2022-03-19 11:39 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/JobsToYaml.kt
> +        require(value > 0) { """Invalid value of field Job(timeoutMinutes=$value)""" }
Let's be more specific here:
```suggestion
        require(value > 0) { """timeout should be positive""" }
```
and I'd also move this validation out of YAML serialization logic. It should happen as soon as the job object is created.

2022-03-19 11:40 UTC, krzema12 requested changes
Looks good overall, I'd just put validation "earlier".

2022-03-19 14:59 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/JobsToYaml.kt
> +        require(value > 0) { """Invalid value of field Job(timeoutMinutes=$value)""" }
i followed the same pattern as the name validation

2022-03-19 15:35 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/JobsToYaml.kt
> +        require(value > 0) { """Invalid value of field Job(timeoutMinutes=$value)""" }
Ok, so we should change the name validation :) I can do it in spare time.

2022-03-20 08:46 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/JobsToYaml.kt
> +        require(value > 0) { """Invalid value of field Job(timeoutMinutes=$value)""" }
#144

2022-03-21 08:09 UTC, krzema12 requested changes

2022-03-21 08:09 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/yaml/JobsToYamlTest.kt
> +    it("should reject invalid timeout values") {
This particular test belongs rather to unit tests of `Job` class because the validation logic is placed there. I already moved name validation, so please rebase onto newest main branch and move this test here

https://github.com/krzema12/github-actions-kotlin-dsl/blob/ef5022ed99e8f8b88cb07741ffbc60a2bdccdcbb/library/src/test/kotlin/it/krzeminski/githubactions/domain/JobTest.kt#L8

2022-03-21 08:09 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
> +    val timeoutMinutes: Int? = null,
I'm wondering if we would like to make it of type `Duration`. Advantage: instead of writing `timeoutMinutes = 30` or `timeoutMinues = 180` we'd write `timeout = 30.minutes` and `timeout = 3.hours` accordingly. Disadvantage: it would require more complex validation to ensure that no seconds or milliseconds part is defined. Maybe this extra validation complexity is worth adding to have nicer API - WDYT? :smile:

2022-03-21 10:45 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
> +    val timeoutMinutes: Int? = null,
i think if somone wants to write with Duration they can do `3.hours.asWholeMinutes` or the like.. but github cannot deal with fractions of minutes or the like and we would HAVE to round it down or up ..
i personally see not complex enough usecases that require `Duration`
 .. if someone wants 3 hours.. do `timeoutMinutes = 3 * 60` or such

2022-03-21 10:48 UTC, NikkyAI commented on library/src/test/kotlin/it/krzeminski/githubactions/yaml/JobsToYamlTest.kt
> +    it("should reject invalid timeout values") {
i moved the new tests to `JobTest` and squashed commits to cleanup stuff

2022-03-21 12:17 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
> +    val timeoutMinutes: Int? = null,
>we would HAVE to round it down or up 

False :) As I wrote, we could validate it in runtime, as we do it now for checking `timeoutMinutes` being positive.

> i personally see not complex enough usecases that require `Duration`

It's not even about complexity, I also don't anticipate performing any arithmetic prior to assigning the timeout to the job. I'm thinking in terms of clean and safe API.

2022-03-21 12:18 UTC, krzema12 requested changes

2022-03-21 12:18 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
> +    val timeoutMinutes: Int? = null,
@jmfayard could you share third opinion? :)

2022-03-21 16:14 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
> +    val timeoutMinutes: Int? = null,
I don't know, if I have a type `Duration` I expect to be able to set any duration, which is not the case, the type doesn't really model what's possible. I would go for an `Int`

2022-03-21 18:19 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
> +    val timeoutMinutes: Int? = null,
Thanks! Let's stay with `timeoutMinutes` snd `Int` for now.

(Other idea, maybe for later: have a custom class that allows only setting X.minutes and Y.hours.)

2022-03-21 22:43 UTC, NikkyAI commented on library/src/test/kotlin/it/krzeminski/githubactions/domain/JobTest.kt
> +        val yaml = jobs.jobsToYaml()
oh, i get it, fixing it now

2022-03-21 22:49 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
> +    val timeoutMinutes: Int? = null,
since the user always calls `job()` we can have a overload of that which could have a `timeoutHours: Int` parameter

2022-03-22 07:50 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
> +    val timeoutMinutes: Int? = null,
It would be confusing to infer what happens if you set both `timeoutMinutes` and `timeoutHours` (e.g. for timeouts 2:30 someone may want to do it). This topic gets unnecessarily complicated as we continue, so let's leave it as is for now :)

2022-03-22 07:58 UTC, krzema12 approved these changes

2022-03-22 07:59 UTC, merged