script-generator
krzema12/github-actions-kotlin-dsl pull request #157
Opened 2022-03-24 10:40 UTC by jmfayard

# What ?

Generate a Kotlin script from an existing YAML workflow

```bash
export URL=https://raw.githubusercontent.com/jmfayard/refreshVersions/main/.github/workflows/publish-mkdocs-website.yml
./gradlew :script-generator:run --args $URL
```

See `script-generator/README.md`

# Why ?

When lots of suffering has been put into making a YAML workflow to work, people are reluctant to start over from scratch with a library they have yet to know. Better the devil you know... And we don't really plan to change the YAML workflow a lot anyway, what's the point ?

Having a script-generator that gives you quickly a script that generates some YAML that you can compare with your existing workflow via https://www.yamldiff.com/ can be a game changer

# How ?

kotlinx-serialization with kaml, plus a pre-processing step because GitHub does crazy shit with its YAML workflows.

kotlinpoet code, with a handy. `Collection.joinToCode()` utility

I try to re-use when possible code that was made for generating the YAML inside the `library` module, using then the new annotation `@InternalGithubActionsApi`

The integration tests from the folder `yaml-input` cover a lots, in my experience the smallest mistake is covered soon with it. And we can add new integration tests easily if we have interesting existing YAML workflows

2022-03-26 22:09 UTC, krzema12 requested changes
I reviewed only the API, the docs, and changes in the library and wrapper-generator. I leave the implementation to you, as agreed about the ownership :)

2022-03-26 22:09 UTC, krzema12 commented on script-generator/build.gradle.kts
> +    testImplementation(project(":library"))
Duplicated (see L22), and also if it's given in `implementation`, it's not needed to specify it in `testImplementation`

2022-03-26 22:11 UTC, krzema12 commented on script-generator/build.gradle.kts
> +    finalizedBy(":library:ktlintFormat")
Should it say `:library`? I guess it's a leftover after copying from wrapper-generator.

2022-03-26 22:22 UTC, krzema12 commented on script-generator/src/main/kotlin/it/krzeminski/githubactions/scriptgenerator/Jobs.kt
> +            enumMemberName<RunnerType>(job.runsOn) ?: enumMemberName(RunnerType.UbuntuLatest)
I'm trying to convert https://raw.githubusercontent.com/krzema12/vis-assert/master/.github/workflows/deploy.yml but the tool returns

```
WARNING: Unexpected enum class it.krzeminski.githubactions.domain.RunnerType macos-latest=macos-latest expected=[Lit.krzeminski.githubactions.domain.RunnerType;@5a12c728
```

Looks like a bug, and I'm wondering if it should just produce a warning, or make the whole run fail (maybe when adding some flag like `--force`, it should behave like now?).

2022-03-28 12:52 UTC, krzema12 commented
I added the [`CODEOWNERS file`](https://github.com/krzema12/github-actions-kotlin-dsl/blob/main/.github/CODEOWNERS), please add this line there:

```
/script-generator/ @jmfayard
```

2022-03-29 15:25 UTC, jmfayard commented on script-generator/src/test/kotlin/test/CaseEnumSerializerTest.kt
> +class CaseEnumSerializerTest : FunSpec({
Done

2022-03-29 15:25 UTC, jmfayard commented on script-generator/README.md
> +## 🎉 Generate your Kotlin Script from your existing YAML workflow
Done, would appreciate if you can review  & improve the mkdocs page that I created

2022-03-29 15:29 UTC, jmfayard commented on script-generator/build.gradle.kts
> +    finalizedBy(":library:ktlintFormat")
Good catch, fixed

2022-03-29 15:29 UTC, jmfayard commented on script-generator/build.gradle.kts
> +    testImplementation(project(":library"))
Fixed

2022-03-29 16:11 UTC, jmfayard commented
@krzema12 Can you have a look at the doc? https://github.com/krzema12/github-actions-kotlin-dsl/blob/7f4724343b47f4f02c6935ea63b802a585dd6306/docs/user-guide/script-generator.md

I'm done with the rest.

2022-03-30 07:20 UTC, krzema12 approved these changes

2022-03-30 07:20 UTC, merged

2022-03-30 07:21 UTC, krzema12 commented
Thank you for this awesome piece of work :) Kudos!

2022-03-30 07:37 UTC, jmfayard commented
thanks a lot :)