Detect newer available version #119
krzema12/github-actions-kotlin-dsl pull request #170
Opened 2022-04-08 10:23 UTC by jmfayard

resolves #119

2022-04-09 19:51 UTC, krzema12 requested changes

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsKtTest.kt
> +class SuggestVersionsKtTest : FunSpec({
```suggestion
class SuggestVersionsTest : FunSpec({
```

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +        // .take(3)
```suggestion
```

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +    OkHttpClient()
A matter of taste, but how about using Ktor client? :) Supports coroutines and (de)serialization with kotlinx.serialization out of the box, is more Kotlin-centric, and I'm personally more familiar with it. I generally follow a rule that there's a library from JetBrains for a certain task, I use it in the first order, and fall back to third-party only if necessary.

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +fun ActionCoords.fetchAvailableVersions(GITHUB_TOKEN: String): List<String> {
```suggestion
fun ActionCoords.fetchAvailableVersions(githubToken: String): List<String> {
```

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +        suggestNewerVersion(existingVersions, available)?.let { message ->
Could we make it return non-zero if some suggestion appears? Thanks to this we'll be able to run it automatically through GitHub workflow and if it exits with non-zero code, it will make the workflow fail and I'll get an e-mail ;) If you have a better idea for the API for this command that would fit this scenario, I'm open.

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +        val coords = list.maxByOrNull { it.version }!!
I try to avoid `!!` to not get mysterious NPEs. Let's use e.g. `?: error("Could not find newest version")` or something similar.

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +            |Create a personal token at https://github.com/settings/tokens
Let's write that the token needs to have `public_repo` scope.

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsKtTest.kt
> +        sortedVersions.sortedBy { VersionComparable(it) } shouldBe sortedVersions
Wait, this test tests almost nothing :) You give it already sorted list.

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsKtTest.kt
> +                    listOf("v1"), listOf("v1.1.1", "v2.0.1", "v3.1.1")
If these tests are for major versions, without minor and patch, I think it should say e.g.
```suggestion
                    listOf("v1"), listOf("v1", "v2", "v3")
```
Same below.

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsKtTest.kt
> +                ) shouldBe "new minor version available: v12.1.2"
The message here is misleading, actually the new major version is available.

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +        val newer = majorVersions.filter { VersionComparable(it) > VersionComparable(maxExisting) }
Instead of keeping versions as strings and wrapping them in `VersionComparable` wherever needed, I suggest renaming `VersionComparable` to just `Version`, instantiating it from strings as soon as possible (e.g. `maxExisting` could already be an instance of `Version`), and then intuitively using it like `it > maxExisting` here.

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +@kotlinx.serialization.Serializable
```suggestion
@Serializable
```

2022-04-09 19:51 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +        if (response.isSuccessful.not()) {
Is there any advantage of this notation over
```suggestion
        if (!response.isSuccessful) {
```
? Is `not()` more prominent in your opinion?

2022-04-10 07:15 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +        suggestNewerVersion(existingVersions, available)?.let { message ->
I was thinking that if the output is not blank, we open an issue with its content exactly like https://github.com/krzema12/github-actions-kotlin-dsl/issues/171

2022-04-10 07:18 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsKtTest.kt
> +        sortedVersions.sortedBy { VersionComparable(it) } shouldBe sortedVersions
Well I assume that `sortedBy { }` is already battle tested and I'm testing `VersionComparable.compareTo()`.
To make things clearer, I have added `Iterable.shuffled()` which change the order

2022-04-10 08:26 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +    OkHttpClient()
@krzema12 I thought about ktor vs okhttp, and for me the main question is: 
- do we want to use coroutines to make things faster by fetching in parallel ?
- or do we want to continue with blocking calls to keep things simpler ?

If we want to use coroutines, we should probably do it in the wrapper generators too (instead of `URI(..).readText()`) because that's the one we run most often.

2022-04-10 08:29 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsKtTest.kt
> +                    listOf("v1"), listOf("v1.1.1", "v2.0.1", "v3.1.1")
That's not how it works.
The list `listOf("v1")` comes from the versions defined in `wrappersToGenerate`.
The list `listOf("v1.1.1", "v2.0.1", "v3.1.1")` is what comes from the HTTP call, and from that we have to understand that `v2` and `v3`  are available.

2022-04-10 08:31 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsKtTest.kt
> +                ) shouldBe "new minor version available: v12.1.2"
What would you suggest ? 
`new hardcoded version` ?

2022-04-10 08:54 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +        if (response.isSuccessful.not()) {
I prefer the `not()` because it keeps a coherent left-to-right reading order.

2022-04-10 08:55 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +        val newer = majorVersions.filter { VersionComparable(it) > VersionComparable(maxExisting) }
Wow that's a great sugestion thanks

2022-04-10 17:18 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +    OkHttpClient()
Right, fetching wrapper metadata in parallel would be a nice thing - we can think about it in the future.
Let's leave okhttp for now.

2022-04-10 17:19 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +        suggestNewerVersion(existingVersions, available)?.let { message ->
Ok, got it - we can try with such API, it's anyway internal to the project so not a big deal. Good idea with automatic issue creation! Are you planning to add such workflow?

2022-04-10 17:21 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsKtTest.kt
> +                ) shouldBe "new minor version available: v12.1.2"
Maybe simply `new version available`?

2022-04-10 17:27 UTC, krzema12 requested changes

2022-04-10 17:27 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +    val data = json.decodeFromString(ListSerializer(GithubTag.serializer()), content)
I think this simpler form will work as well:
```suggestion
    val data = json.decodeFromString<List<GithubTag>>(content)
```

2022-04-10 17:27 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsTest.kt
> +                    "v2".versions(), "v1.1.1, v2.0.1, v3.1.1".versions()
Continuation of https://github.com/krzema12/github-actions-kotlin-dsl/pull/170#discussion_r846739735

I get what you meant, but suggesting that `v3` is available where there's no explicit `v3` tag for a given action looks like an overinterpretation. I think we should suggest `v3` only if the tag `v3` exists, and if a tag with minor/path exists, we shouldn't suggest it  - it would then mean that the action maintainer messed something with released versions and didn't release the major version-based one.

2022-04-11 13:13 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +    val data = json.decodeFromString(ListSerializer(GithubTag.serializer()), content)
No, that doesn't work because of type erasure.

2022-04-11 13:45 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsTest.kt
> +                    "v2".versions(), "v1.1.1, v2.0.1, v3.1.1".versions()
You were right, I thought the tag "v2" weren't available in the APi results but they actually are.
I have fixed the logic.
I also now detect if we are using an hardcoded version like `v2.1.0` but an explicit version `v2` is available

2022-04-11 14:10 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsKtTest.kt
> +                    listOf("v1"), listOf("v1.1.1", "v2.0.1", "v3.1.1")
I was wrong, logic updated, see comment below

2022-04-11 14:17 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +        suggestNewerVersion(existingVersions, available)?.let { message ->
Yes, almost written already, will submit in a separate pull request

2022-04-11 14:18 UTC, jmfayard commented
@krzema12 I am almost done, except for the workflow to create an issue, which I will submit in a separate pull request

2022-04-11 16:24 UTC, krzema12 requested changes

2022-04-11 16:24 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +    val data = json.decodeFromString(ListSerializer(GithubTag.serializer()), content)
"Works on my machine" ;) This overload of `decodeFromString` is `reified`:

```kotlin
fun main() {
    val content = "[{\"ref\": \"some-ref\"}, {\"ref\": \"12334\"}]"
    val data = json.decodeFromString<List<GithubTag>>(content)
    println(data)  // [GithubTag(ref=some-ref), GithubTag(ref=12334)]
}
```

2022-04-11 16:24 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> + * new major version(s) available: [v3] for ActionCoords("actions", "cache", "v2")
I think this output format is outdated, it now displays either `""` or `"*"` as version. It looks a bit weird. Could we either go back to what this comment shows, or if there's some problem with it, update this comment?

2022-04-11 16:24 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Version.kt
> +    override fun compareTo(other: Version): Int {
nit. some spacing before the function please:
```suggestion

    override fun compareTo(other: Version): Int {
```

2022-04-11 16:24 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsTest.kt
> +class SuggestVersionsTest : FunSpec({
Let's have a test for this peculiar edge case of some actions that specify the version as `latest`, or to generify, something that doesn't resemble a version number:

https://github.com/krzema12/github-actions-kotlin-dsl/blob/a7b9bb4a98e9ce1ac79cf00081f9f0ae998f08b9/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt#L588

2022-04-11 17:20 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> + * new major version(s) available: [v3] for ActionCoords("actions", "cache", "v2")
I didn't know what to put there since we coulud have mulutiple versions

2022-04-11 17:26 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> + * new major version(s) available: [v3] for ActionCoords("actions", "cache", "v2")
Ok, so updating the comment or maybe even removing it (so that it won't get outdated anymore) will be ok :)

2022-04-11 20:24 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> + * new major version(s) available: [v3] for ActionCoords("actions", "cache", "v2")
done

2022-04-11 20:24 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Version.kt
> +    override fun compareTo(other: Version): Int {
Done

2022-04-11 20:33 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersionsTest.kt
> +class SuggestVersionsTest : FunSpec({
done

2022-04-11 20:35 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +    val data = json.decodeFromString<List<GithubTag>>(content)
You were right, I didn't have the right import

2022-04-11 20:35 UTC, jmfayard commented
I'm done here

2022-04-11 20:35 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/Http.kt
> +    val data = json.decodeFromString(ListSerializer(GithubTag.serializer()), content)
You were right, fixed

2022-04-12 04:09 UTC, merged