Workflow that creates an issue with available updates
krzema12/github-actions-kotlin-dsl pull request #178
Opened 2022-04-11 15:09 UTC by jmfayard

Depends on https://github.com/krzema12/github-actions-kotlin-dsl/pull/170

2022-04-11 16:01 UTC, krzema12 requested changes

2022-04-11 16:01 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +    var output: String = ""
What if this variable remains empty? Will the workflow create the issue as well?

2022-04-11 16:05 UTC, jmfayard commented on .github/workflows/updates-available.main.kts
> +            action = CustomAction(
Yes but then we can't test the workflow until the library is released

2022-04-11 16:14 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +    var output: String = ""
That would be great but currently not.
We could make `gradlew suggestVersions` fails, but then you receive an email so it's not better.
Ideally we would add a `condition = fileNotExists("suggestVersions.md)` but I'm afraid I don't know how to do that.

2022-04-11 16:25 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/versions/SuggestVersions.kt
> +    var output: String = ""
Ok, let's keep it simple - we can resolve an empty ticket twice a month, worst case :)

2022-04-11 16:31 UTC, krzema12 commented on .github/workflows/actions-versions.main.kts
> +            Cron(dayMonth = "1,16", hour = "7", minute = "0")
Let's make it once a week - that often I'm planning to release new versions, ideally.

2022-04-11 16:36 UTC, jmfayard commented on .github/workflows/actions-versions.main.kts
> +            Cron(dayMonth = "1,16", hour = "7", minute = "0")
Done, I've make it on fridays, you change change it to suit your needs

2022-04-11 17:07 UTC, krzema12 approved these changes

2022-04-11 19:13 UTC, krzema12 approved these changes

2022-04-12 09:18 UTC, jmfayard commented
@krzema12 conflicts solved

2022-04-12 12:11 UTC, krzema12 approved these changes

2022-04-12 12:13 UTC, merged