Workflow.concurrency and Job.concurrency
krzema12/github-actions-kotlin-dsl pull request #184
Opened 2022-04-14 17:36 UTC by jmfayard

Resolves #119

2022-04-16 18:57 UTC, krzema12 requested changes

2022-04-16 18:57 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/Concurrency.kt
> +package it.krzeminski.githubactions.dsl
It should rather be in the domain package:
```suggestion
package it.krzeminski.githubactions.domain
```

2022-04-16 18:57 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/Concurrency.kt
> + * Using concurrency allow to run a workflow/job at a time
Minor grammar issues:
```suggestion
 * Using concurrency allows running single workflow/job at a time
```
does it still preserve the meaning it should, after my fixes? :)

2022-04-16 18:57 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +        if (concurrency != null) {
Could you move it below the triggers ("on:")? It seems to be less important.

2022-04-17 09:48 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/Concurrency.kt
> +package it.krzeminski.githubactions.dsl
done

2022-04-17 09:48 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/ToYaml.kt
> +        if (concurrency != null) {
done

2022-04-17 09:48 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/Concurrency.kt
> + * Using concurrency allow to run a workflow/job at a time
yes it does :)

2022-04-17 09:48 UTC, jmfayard commented
I'm done

2022-04-19 07:21 UTC, krzema12 approved these changes

2022-04-19 07:21 UTC, merged

2022-04-19 07:22 UTC, krzema12 commented
Thank you! :guitar: