[#203] type-safe expressions
krzema12/github-actions-kotlin-dsl pull request #204
Opened 2022-04-21 14:06 UTC by jmfayard

**What**

type-safe expressions

**How**

see tests

**what's missing**

lots of stuff

**Doc**

- [Functions](https://docs.github.com/en/actions/learn-github-actions/expressions#functions)
- [Default environment variables](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables)
- [contexts](https://docs.github.com/en/actions/learn-github-actions/contexts)
- [Context availability](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability)
- [Webhook events and payloads](https://docs.github.com/-en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads)

2022-04-21 18:47 UTC, jmfayard commented on .github/workflows/expr-testing.yml
> +      $GREETING: World
On every `env`, I would need to add a pre-processing step `key.removePrefix("\$")`

2022-04-21 18:49 UTC, jmfayard commented on .github/workflows/expr-testing.yml
> +        matrix.NODE:
I would need to add a pre-processing step `key.removePrefix("matrix.")`

2022-04-21 20:08 UTC, jmfayard commented on .github/workflows/expr-testing.yml
> +      $GREETING: World
Done

2022-04-21 20:08 UTC, jmfayard commented on .github/workflows/expr-testing.yml
> +        matrix.NODE:
Done

2022-04-22 08:33 UTC, jmfayard commented
Type-safe expressions are now ready for review 🎉

2022-04-29 10:03 UTC, krzema12 requested changes
Shared some initial feedback. Looks cool already :rocket:

2022-04-29 11:09 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/expr/GitHubContext.kt
> +    val token by map
No they are currently hand-crafted from the documentation at https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

The class that can be generated from a json is `github.event` which depends on the even (pull request vs push vs ...) but I decided not include it because I think few people use it.

For a data-driven approach, we can have a workflow that runs `{{ toJSON(github) }}` on the CI and add a unit test that makes sure that the keys of the resulting JSON match exactly the properties of `GitHubContext` (via reflection)

2022-04-29 11:11 UTC, jmfayard commented on .github/workflows/expr-testing.yml
> +name: expr-typesafe
Right, I wanted to be sure that the workflow is valid and runs on GitHub action, I can now transform that in a unit test.

2022-04-29 11:22 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/JobsToYaml.kt
> +            val strategyParam = rawStrategyParam.removePrefix("matrix.")
It does look hacky on the implementation side, but it's very practical from the user point of view : 

You create a type-safe variable for either an environment variable `Expr.env` or a strategy matrix `Expr.matrix`.
Depending on where you use it it takes a different value but you don't have to care about that.

![github-actions-kotlin-dsl_–_ExprIntegrationTest_kt__github-actions-kotlin-dsl_library_test_](https://user-images.githubusercontent.com/459464/165935181-013d4877-87ce-4ea0-9bd7-3a47e11abc52.png)

2022-04-29 12:08 UTC, jmfayard commented on library/src/test/kotlin/it/krzeminski/githubactions/dsl/ExprIntegrationTest.kt
> +class ExprIntegrationTest : FunSpec({
done

2022-04-29 12:09 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/expr/GitHubContext.kt
> +    val repositoryUrl by map
Yep it looks like I made a mistake but no :)

2022-04-29 13:22 UTC, jmfayard commented
I don't understand, I have an error `java.lang.NoClassDefFoundError: com/charleskorn/kaml/MalformedYamlException` when I try to execute the workflow with `@file:DependsOn("it.krzeminski:github-actions-kotlin-dsl:0.15.0")`
`

2022-04-29 14:40 UTC, krzema12 commented
> I don't understand, I have an error `java.lang.NoClassDefFoundError: com/charleskorn/kaml/MalformedYamlException` when I try to execute the workflow with `@file:DependsOn("it.krzeminski:github-actions-kotlin-dsl:0.15.0")` `

Interesting, could you create a bug for it, along with a reproducer?

2022-04-29 20:45 UTC, jmfayard commented
Open to feedback but I'm done feature wise.
I would like to try to generate the context classes for the various `github.event` but I would do that in a separate pull request

2022-06-18 10:33 UTC, Vampire commented
Nice work from a first look.
But you said you left out the steps context due to output being available already.
But there is more to it, for example outcome and conclusion.

2022-06-25 07:48 UTC, krzema12 commented
@jmfayard I'm planning to revisit it next week, sorry to keep you waiting. Could you please rebase on newest `main`? I also thought we could have a smaller change first that would add `expr {}` API and support for just one simple context. After we iterate on it and merge it, adding more contexts in small separate PRs should be easy. Would you be ok with it?

2022-06-25 09:00 UTC, jmfayard commented
https://github.com/krzema12/github-actions-kotlin-dsl/pull/313 only `expr {{ runner.xxx }}`

Splitted from https://github.com/krzema12/github-actions-kotlin-dsl/commit/3341cd22b2c60b01fcf17f0039ea7962d55c8a27

2022-06-30 18:22 UTC, jmfayard commented
Closed, super-seded by 3 smaller pull requests

2022-06-30 18:22 UTC, closed without merging