Split integration tests and make them run on GitHub
krzema12/github-actions-kotlin-dsl pull request #229
Opened 2022-04-29 23:50 UTC by jmfayard

Solves #87 

Each workflow from `IntegrationTest` is defined in its own file.

Each expected YAML is defined in resources/integration/expected/$NAME.yaml

If the test fails, the actual YAML is written to resources/integration/actual/$NAME.yaml

Add a new workflow who copy the YAML worklows to a separate repository;

TODO @krzema12

- create a secret PRIVATE_ACCESS_TOKEN
- fork my repo https://github.com/jmfayard/github-actions-integration

Unfortunately it is forbidden by GitHub to push YAML files inside `.github/workflows`, probably to avoid infinite loops

See https://github.com/EndBug/add-and-commit/issues/342

So right now we have to run `copy.sh` https://github.com/jmfayard/github-actions-integration

2022-04-30 08:27 UTC, jmfayard commented
I simplified my solution which now works with a shell script + a separate repository currently  https://github.com/jmfayard/github-actions-integration

2022-07-05 05:52 UTC, krzema12 requested changes

2022-07-05 05:52 UTC, krzema12 commented on integration.sh
> +REPO="https://github.com/jmfayard/github-actions-integration"
I'm wondering if it's needed to use another repo just to copy the workflows there. The downside of it is that we don't have any feedback whether the workflow runs were successful in that repo, unless we somehow query GitHub about it.

If our goal is to simply run the generated workflows, we could store and run them in this repo (github-actions-kotlin-dsl), as part of regular verification. We could name them well, like starting with "Integration test: ...", and leave what you've already added regarding comparing actual and expected output. The only downside I see so far: it will be tricky to put consistency check in the workflows because then they would need a source script to call (not sure if it's addressed correctly in your current solution).

To avoid wasted effort during iteration, how about we try out this approach for a single test and then iterate over it? Let me know if you have time to do it, or I should do it - will be happy to give it a shot :smile:

2022-07-05 05:52 UTC, krzema12 commented on integration.sh
> +#!/usr/bin/env bash
Did you mean to call this file from some workflow? I cannot find it.

2022-07-05 05:52 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/kotest/ShouldMatchFile.kt
> +infix fun String.shouldMatchFile(path: String) {
We already have this file committed in a simplified form, so this change needs rebasing.

2022-08-10 06:00 UTC, krzema12 commented
Replaced with something simpler, see the commits in #87.

2022-08-10 06:00 UTC, closed without merging