Create files `action-types.yml` for each Wrapper Request
krzema12/github-actions-kotlin-dsl pull request #308
Opened 2022-06-22 20:54 UTC by jmfayard

I added a method that use the wrapper requests and generate its corresponding  `action-types.yml` for each wrapper request

If the spec at https://github.com/krzema12/github-actions-typing changes, just adapt `fun Typing.type(): ActionType` and regenerate the YAML files

There is also `action-types/README.md` to make it even easier to submit a pull request

https://github.com/krzema12/github-actions-kotlin-dsl/blob/action-types/actions-types/README.md

2022-06-23 14:24 UTC, krzema12 requested changes
Awesome, thanks for this, I was thinking of it as well! :) Left some comments while on the go, will review in detail later.

2022-06-23 14:24 UTC, krzema12 commented on actions-types/10up-action-wordpress-plugin-deploy-v2.0.0.yml
> +typingSpec: 10up/action-wordpress-plugin-deploy@v2.0.0
It should be equal to `typingSpec: krzema12/github-actions-typing@v0.3` for each action. I'm planning to specify minor versions for v0 because of likely frequent breraking changes, but starting from v1 only major version will be specified).

2022-06-23 14:24 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/types/ActionTypes.kt
> +    val inputs: Map<String, ActionType> = emptyMap()
Could we also include outputs here, even if we don't have info about their type (use `string`)? It will save time on checking what outputs the action has, only types may require adjustment.

2022-06-23 17:42 UTC, jmfayard commented on actions-types/10up-action-wordpress-plugin-deploy-v2.0.0.yml
> +typingSpec: 10up/action-wordpress-plugin-deploy@v2.0.0
done

2022-06-23 17:42 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/types/ActionTypes.kt
> +    val inputs: Map<String, ActionType> = emptyMap()
done

2022-06-23 17:43 UTC, jmfayard commented
@krzema12 I have added the outputs but obviously they are all of type string since we don't have the concept of `outputTypings`

2022-06-23 18:30 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/types/ActionTypes.kt
> +    @SerialName("float") Float,
Yes, I'm aware - no action ever needed it yet in our lib, but I decided to add it to the spec as it's usually one of basic types in multiple programming languages.

2022-06-23 20:05 UTC, krzema12 commented
Windows test fails because of `contents match, but line-breaks differ`. I'd recommend generating the YAMLs with Linux new lines, seems like GitHub favors Linux overall 😄

2022-06-23 20:10 UTC, krzema12 commented on actions-types/10up-action-wordpress-plugin-deploy-v2.0.0.yml
> +    type: string
Just wondering if it wouldn't be too hard to put a comment at the end of each output type like `# please check this output's description and set proper type! String is just set by default`. Maybe kotlinx.serialization and kaml allows putting comments?

2022-06-23 21:59 UTC, jmfayard commented on actions-types/10up-action-wordpress-plugin-deploy-v2.0.0.yml
> +    type: string
done

2022-06-23 22:08 UTC, jmfayard commented
All done @krzema12

2022-06-24 05:09 UTC, krzema12 commented
Looks good, thanks a lot @jmfayard! I just rearranged the commits a bit.

Now I'm planning to post PRs with these files for several actions. I'll skip actions owned by GitHub as I'd like to work with independent authors first before we start talking to GitHub. I'll look for 5 actions that are actively maintained and will post PRs analogical to this one: https://github.com/Vampire/setup-wsl/pull/30

2022-06-24 05:09 UTC, krzema12 approved these changes

2022-06-24 05:09 UTC, merged