type-safe environment variables and secrets
krzema12/github-actions-kotlin-dsl pull request #324
Opened 2022-06-28 11:14 UTC by jmfayard

See:

- Environment variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables#about-environment-variables
- Default Environment variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

2022-06-28 11:20 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/ExpressionContext.kt
> +    internal val _path: String,
`path`  doesn't work, there are contexts with a property called `path`

2022-06-28 11:20 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/ExpressionContext.kt
> +    val map: Map<String, String> = MapFromLambda { propertyName -> "$_path.$propertyName" }
we can revert to `propertyToExprPath` but that feels weird to me

2022-06-28 11:20 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/ExpressionContext.kt
> +internal class MapFromLambda<T>(val operation: (String) -> T) : Map<String, T> by emptyMap() {
If it's private, I can't use it in `Env` and `Secrets`

2022-06-28 11:20 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/ExpressionContext.kt
> +): Map<String, String> by map
`val TOKEN by Env` instead of `by Env.map`

`val SUPER_SECRET by Secrets` instead of `by Secrets.map`

2022-06-28 11:20 UTC, jmfayard commented on library/src/test/resources/expected/workflow-expr-typesafe.yml
> +          TOKEN: ${{ secrets.GITHUB_TOKEN }}
Without the change to `fun LinkedHashMap<String, String>.toYaml()` that would be:

`$SECRET: ${{ secrets.SUPER_SECRET }}`

That the one place where we don't want this behavior

2022-06-28 13:41 UTC, krzema12 requested changes

2022-06-28 13:41 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/Env.kt
> +package it.krzeminski.githubactions.dsl.expressions
Should be in 
```suggestion
package it.krzeminski.githubactions.dsl.expressions.contexts
```

`Secrets` as well.

2022-06-28 13:41 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/ExpressionContext.kt
> +    internal val _path: String,
True!

2022-06-28 13:41 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/ExpressionContext.kt
> +    val map: Map<String, String> = MapFromLambda { propertyName -> "$_path.$propertyName" }
I wanted to come up with anything more meaningful than `map`, but I agree that `propertyToExprPath` does look weird. Maybe simply `contextProperty`?

Please also revert the renaming in this commit and let's rename it in a separate one, to avoid noise.

2022-06-28 13:41 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/Secrets.kt
> +object Secrets : ExpressionContext("secrets", MapFromLambda { key: String -> "secrets.$key" }) {
Why is it needed to pass the second constructor argument? Won't the default work here?

Also, `SecretsContext` for consistency.

2022-06-28 13:41 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
> +            val SUPER_SECRET by Secrets
Could we somehow differentiate how custom values are defined? Now it's not clear and one may think that `SUPER_SECRET` is a part of GitHub-provided context. How about:

```suggestion
            val SUPER_SECRET by Secrets.custom
```
? Any thoughts?

2022-06-28 13:41 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/Utils.kt
> +        val key = rawKey.removePrefix("\$")
Can it be encapsulated in `Env`, the logic inside `MapFromLambda`?

2022-06-28 13:41 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/Env.kt
> +object Env : ExpressionContext(_path = "env", map = MapFromLambda { key: String -> "\$$key" }) {
```suggestion
object EnvContext : ExpressionContext(_path = "env", map = MapFromLambda { key: String -> "\$$key" }) {
```

2022-06-28 13:41 UTC, krzema12 commented on library/src/test/resources/expected/workflow-expr-typesafe.yml
> +          TOKEN: ${{ secrets.GITHUB_TOKEN }}
Let's discuss another approach where to handle it - I added a comment in `toYaml()`.

2022-06-28 13:47 UTC, krzema12 commented
Sorry for failing "Check if wrappers up to date" check - as we have more actions, it happens more and more frequently. We have fixing it on the radar as https://github.com/krzema12/github-actions-kotlin-dsl/issues/208.  For the purpose of this PR you can ignore it, I'll handle it.

2022-06-28 13:57 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/Secrets.kt
> +package it.krzeminski.githubactions.dsl.expressions
```suggestion
package it.krzeminski.githubactions.dsl.expressions.contexts
```

2022-06-28 14:35 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/Utils.kt
> +        val key = rawKey.removePrefix("\$")
The logic inside `EnvContext` is to add the dollar, because without it, instead you would have to write this which is error-prone

```kotlin
run(
    name = "Default environment variable",
-    command = "action=${Contexts.env.GITHUB_ACTION} repo=${Contexts.env.GITHUB_REPOSITORY}",
+   command = "action=\$${Contexts.env.GITHUB_ACTION} repo=\$${Contexts.env.GITHUB_REPOSITORY}",
)
```

The reason I have put it there is that modifying all places where we can have a `env` looks like a lot of work
<img width="999" alt="github-actions-kotlin-dsl_–_Step_kt__github-actions-kotlin-dsl_library_main_" src="https://user-images.githubusercontent.com/459464/176204715-4bc74a84-47a8-494f-8cfb-fe56703361a4.png">

2022-06-28 14:39 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/expressions/ExpressionContext.kt
> +    val map: Map<String, String> = MapFromLambda { propertyName -> "$_path.$propertyName" }
done

2022-06-29 02:16 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/yaml/Utils.kt
> +        val key = rawKey.removePrefix("\$")
Ok, I think I get it now. It depends on the context if we want to have the dollar in resulting YAML and here's the best place to express this knowledge.

2022-06-29 02:20 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
> +            val SUPER_SECRET by Secrets
Ok I wasn't aware of this naming convention :) Here I pointed it out looking purely on library's API. Let's leave it as is for now and see how it works in practice.

2022-06-29 02:22 UTC, krzema12 approved these changes

2022-06-29 02:24 UTC, merged