Add AndroidEmulatorRunnerV2
krzema12/github-actions-kotlin-dsl pull request #345
Opened 2022-07-15 15:13 UTC by LeoColman

2022-07-15 15:55 UTC, jmfayard requested changes
Thanks for your contribution
We have typings though to make things more type safe and right now they have to be deduced manually and put into `wrapperstogenerate`

2022-07-15 15:55 UTC, jmfayard commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/reactivecircus/AndroidEmulatorRunnerV2.kt
> +public class AndroidEmulatorRunnerV2(
Please add typings in `wrapperstotenerate` to make the class type safe and easier to use

2022-07-15 15:55 UTC, jmfayard commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/reactivecircus/AndroidEmulatorRunnerV2.kt
> +    public val cores: String? = null,
This can be an int

2022-07-15 16:03 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("ReactiveCircus", "android-emulator-runner", "v2.25.0")
Please use major version - the action provides a `v2` tag: https://github.com/ReactiveCircus/android-emulator-runner/tree/v2

2022-07-15 16:09 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/WrappersToGenerate.kt
> +        ActionCoords("ReactiveCircus", "android-emulator-runner", "v2.25.0")
```suggestion
        ActionCoords("ReactiveCircus", "android-emulator-runner", "v2")
```
Please use major version - the action provides a `v2` tag: https://github.com/ReactiveCircus/android-emulator-runner/tree/v2

2022-07-15 16:11 UTC, krzema12 commented
>...right now they have to be deduced manually and put into `wrapperstogenerate`

@LeoColman unless you can ask the action owner to provide the typings by onboarding https://github.com/krzema12/github-actions-typing :) Then this PR would be literally an one-liner + generated code.

2022-07-15 20:39 UTC, krzema12 requested changes
There's a failed build - ktlint complains, could you fix the style?
Also let me ensure that you've seen my recommendation to ask the owner to provide the typings in the action itself. I've documented it in the contribution guidelines: https://github.com/krzema12/github-actions-kotlin-dsl/blob/19783861f4ba2eddc28fc2f2085ba1f7ca3e7b45/CONTRIBUTING.md?plain=1#L18 this is non-blocking for this PR, but would be good to do it simultaneously :smile:

2022-07-15 20:41 UTC, krzema12 commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/reactivecircus/AndroidEmulatorRunnerV2.kt
> +     * 10
@LeoColman Have you considered making it an int with named values? See e. g. actions/checkout and fetch-depth. Each API level could have a name assigned to the version integer

2022-07-16 11:34 UTC, LeoColman commented
> There's a failed build - ktlint complains, could you fix the style? Also let me ensure that you've seen my recommendation to ask the owner to provide the typings in the action itself. I've documented it in the contribution guidelines:
> 
> https://github.com/krzema12/github-actions-kotlin-dsl/blob/19783861f4ba2eddc28fc2f2085ba1f7ca3e7b45/CONTRIBUTING.md?plain=1#L18
> this is non-blocking for this PR, but would be good to do it simultaneously smile

Ah, I thought it was more of an OR xD
Let me drop a PR to the action, it will be easier that way for the authors

2022-07-16 14:27 UTC, LeoColman commented
Complementary PR:
https://github.com/ReactiveCircus/android-emulator-runner/pull/257

2022-07-16 14:30 UTC, LeoColman commented
Also, I've fixed the KTlint requirement.

2022-07-16 14:33 UTC, LeoColman commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/reactivecircus/AndroidEmulatorRunnerV2.kt
> +     * 10
I haven't.
Would it be a 1:1 map on Android API and Int?

2022-07-16 14:43 UTC, krzema12 commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/reactivecircus/AndroidEmulatorRunnerV2.kt
> +     * 10
I think so, see https://apilevels.com/

2022-07-16 14:55 UTC, krzema12 commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/reactivecircus/AndroidEmulatorRunnerV2.kt
> +     * 10
Also let me ask: in the Android world, is it more common to use API numbers or names like Marshmallow? Maybe this should be our guide to help us decide how to type this input.

2022-07-22 05:03 UTC, krzema12 commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/reactivecircus/AndroidEmulatorRunnerV2.kt
> +     * 10
@LeoColman friendly ping - do you think the integer would be intuitive enough here?

2022-07-22 21:10 UTC, LeoColman commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/reactivecircus/AndroidEmulatorRunnerV2.kt
> +     * 10
I think it would be intuitive, yes.
I'm not really from the Android world, but it's more usual to me to use API numbers than the version.

"Supports 21+" is easier on my eyes than "Supports Lollipop+"

In the official docs, both are listed, but to me there it seems to have more emphasis on the API Level
https://developer.android.com/studio/releases/platforms

2022-07-22 21:11 UTC, LeoColman commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/reactivecircus/AndroidEmulatorRunnerV2.kt
> +     * 10
API Level is more universal, IMO, while Android Version and Codename are not that usual to me

2022-07-22 21:14 UTC, LeoColman commented on library/src/gen/kotlin/it/krzeminski/githubactions/actions/reactivecircus/AndroidEmulatorRunnerV2.kt
> +     * 10
To further develop my anecdote, I just remember that 21 = lollipop, but I have to search to find the others xD

2022-07-23 05:18 UTC, krzema12 approved these changes

2022-07-23 05:20 UTC, jmfayard approved these changes
LGTM

2022-07-23 05:21 UTC, krzema12 commented
@LeoColman thanks for this! I'll take care of merging.

2022-07-24 16:01 UTC, krzema12 commented
Merging in #357.

2022-07-24 16:01 UTC, closed without merging