add output mapping
krzema12/github-actions-kotlin-dsl pull request #432
Opened 2022-08-30 16:49 UTC by NikkyAI

this adds support for https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs

specifically adding mapping of a specifc steps output to the output of the job
and accessing the outputs of the job from other jobs (assuming `needs` is also setup)

adding output mappings
```kotlin
//with raw commands
run(
     name = "set output",
     command = """echo "::set-output name=test::value"""",
)
   .withOutputMapping("someOutput", "test")

// with typed outputs
uses(SetupPythonV4())
    .withOutputMapping("pythonVersion") { pythonVersion }
```

using output mappings from another job

```kotlin
val someOutput by Contexts.outputs(otherJob)
val pythonVersion by Contexts.outputs(otherJob)
```

2022-08-31 08:33 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
> +                    .withOutputMapping("test", "test")
Regarding the API, I'm thinking about something safer and in line with what we have for step outputs: . Not properly type-safe yet because of the strings, but at least output names would be defined once:

```kotlin
workflow(
    name = "Test workflow",
    on = listOf(Push()),
    sourceFile = gitRootDir.resolve(".github/workflows/some_workflow.main.kts"),
) {
    // define model for job's output. Use it to set the output in job no. 1 and retrieve it in job no. 2
    data class SetOutputJobOutputs(
        val test: String,
        val pythonVersion: String,
    )

    val setOutputJob = job<SetOutputJobOutputs>(
        id = "set_output",
        runsOn = RunnerType.UbuntuLatest,
    ) {
        val setupPython = uses(SetupPythonV4())
        // Use existing mechainsm to retrieve the step output, and new API to set job output
        // I'm not sure if we'd need to make the SetOutputJobOutputs fields mutable, or maybe use some
        // delegated properties magic, but such syntax would be really cool and convenient.
        // I assume that jobOutput is available in the receiver of this job lambda.
        jobOutputs.pythonVersion = setupPython.outputs.pythonVersion

        run(
            name = "set output",
            command = """echo "::set-output name=test::value"""",
        )
        // TODO: there's no support for step outputs for the custom command step,
        // we may need to add it first
    }

    job(
        id = "use_output",
        runsOn = RunnerType.UbuntuLatest,
        needs = listOf(setOutputJob),
    ) {
        run(
            name = "use output test",
            // Use it similarly like step outputs
            command = """echo ${expr { setOutputJob.outputs.test }}""",
        )
        run(
            name = "use output pythonversion",
            command = """echo ${expr { setOutputJob.outputs.pythonVersion }}""",
        )
    }
}

```

2022-08-31 09:04 UTC, NikkyAI commented on library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
> +                    .withOutputMapping("test", "test")
tempting to make Job have a type parameter, will probably have to make sure to make it with mutable variables

or something like this maybe ?

```
class SetOutputJobOutputs {
    var pythonVersion by Outputs.register()
}
```

2022-08-31 12:36 UTC, NikkyAI commented on library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
> +                    .withOutputMapping("test", "test")
i think i can approximate the desired api to some degree

added a `ComandStepWithOutput<T>`  and extension function on `CommandStep`  to convert them (and add the outputs)

generics on `Job` affect a lot of things, i opted for making their default output type Unit  to avoid duplicating more types 
 
and we can make it even closer by adding a overload to` fun expr(block: () -> String)): String`  that accepts non string in the block and converts them to the references (but the typesystem did not like my approach, so i skipped that for now)

2022-08-31 13:02 UTC, NikkyAI commented on library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
> +                    .withOutputMapping("test", "test")
i managed to get the API very close to your desired form i think

```kotlin
val setOutputJob = job(
    id = "set_output",
    runsOn = RunnerType.UbuntuLatest,
    outputs = object : JobOutputs() {
        var pythonVersion: String by createOutput()
        var bar: String by createOutput()
    }
) {
    val commandStepWithOutput = run(
        name = "set output",
        command = """echo "::set-output name=foo::baz"""",
    ).withOutputs(object : StepOutputs() {
        val foo by property()
    })
    jobOutputs.bar = commandStepWithOutput.outputs.foo

    val setupPython = uses(SetupPythonV4())
    jobOutputs.pythonVersion = setupPython.outputs.pythonVersion
}

job(
    id = "use_output",
    runsOn = RunnerType.UbuntuLatest,
    needs = listOf(setOutputJob),
) {
    run(
        name = "use output test",
        command = """echo ${expr { setOutputJob.jobOutputs.bar }}""",
    )
    run(
        name = "use output pythonversion",
        command = """echo ${expr { setOutputJob.jobOutputs.pythonVersion }}""",
    )
}
```

PS: delegates can be a pain in the ass

2022-09-01 20:13 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/IntegrationTest.kt
> +    test("outputs - access outputs across job") {
Before we dig into the implementation details, let's first make this test runnable on GitHub. See other tests in this file with `testRanWithGitHub`. It will generate a YAML in .github/workflows which you have to check in, and then it will be ran by GitHub on next push to your branch.

2022-09-03 15:59 UTC, krzema12 requested changes

2022-09-03 15:59 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/JobBuilder.kt
> +    fun <T : StepOutputs> CommandStep.withOutputs(
Adding command step with outputs seems out of scope of adding job outputs. Could you post a separate, smaller PR that adds **only** command step with outputs? We'll discuss its API there.

2022-09-04 11:50 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/dsl/JobBuilder.kt
> +    fun <T : StepOutputs> CommandStep.withOutputs(
yes, i will remove it from this PR, it is probably not even necessary for my purpose since i can use github-script easier..

2022-09-07 19:55 UTC, krzema12 requested changes

2022-09-07 19:55 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/StepOutputs.kt
> +open class StepOutputs {
Looks like leftover after the previous extended PR, can you remove this file?

2022-09-07 19:55 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/JobOutputs.kt
> +open class JobOutputs {
This class has mixed responsibilities: it serves both as a domain class and contains pieces of GitHub YAML serialization logic. Please split it, or let me know if I should do it.

2022-09-07 19:55 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
> +        operator fun invoke(
Why is it needed to implement this operator? It looks like you wanted to have a secondary constructor. What's your intent exactly?

2022-09-08 08:27 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/Job.kt
> +        operator fun invoke(
that was my solution to keep the old calling convention without changing how `Job` is constructed all over the codebase while i was still tweaking it..
we can remove that

2022-09-08 08:31 UTC, NikkyAI commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/JobOutputs.kt
> +open class JobOutputs {
feel free to tackle that, not sure how you want it split

2022-09-19 06:03 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/yaml/JobsToYamlTest.kt
> +                outputs = JobOutputs.EMPTY,
TODO for myself: add a test case for non-empty outputs.

2022-09-19 06:39 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/JobOutputs.kt
> +open class JobOutputs {
TODO for myself: try to split it so that `Ref` goes into `dsl` package, and `domain` contains only what's needed.

2022-09-20 20:41 UTC, krzema12 approved these changes

2022-09-20 20:45 UTC, krzema12 commented
@NikkyAI thanks a lot for this contribution! :guitar: :rocket:

2022-09-20 20:46 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/domain/JobOutputs.kt
> +open class JobOutputs {
I gave it a shot, but it's not that easy. I decided to leave it as is and see how it works in practice.

2022-09-20 20:46 UTC, merged