3 actions and workflow RefreshVersions-PR
krzema12/github-actions-kotlin-dsl pull request #62
Opened 2022-01-31 17:09 UTC by jmfayard

I added three actions:

- action: AddAndCommitV8 https://github.com/EndBug/add-and-commit
- action: CreateBranchV210 https://github.com/peterjgrainger/action-create-branch
- action: PullRequestV2 https://github.com/repo-sync/pull-request 

With them, I was to built the challenge I had for myself to convert to Kotlin
the YAML workflow from this article https://akjaw.com/keeping-gradle-dependencies-up-to-date-with-github-actions-and-refreshversions/
which brings dependabot-like feature to my software https://jmfayard.github.io/refreshVersions/

Actually I am only almost able to make it work, I need support for GitHub variables https://github.com/krzema12/github-actions-kotlin-dsl/issues/26

2022-01-31 19:47 UTC, krzema12 requested changes
Wow, great to see it almost works for your use case!
I did a partial review due to time constraints, marking changes that need to be made for sure. I'll be back once fixed :smiley:

2022-01-31 19:47 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/PullRequestV2.kt
> +) : Action("repo-sync", "pull-request", "v2.6.1") {
Please use major version (`v2`).

2022-01-31 19:47 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/AddAndCommitV8.kt
> +@Suppress("ConstructorParameterNaming")
Actually `camelCase` is the convention here (see other wrappers) :smile:

The same for two other classes.

2022-01-31 19:47 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/AddAndCommitV8.kt
> +package it.krzeminski.githubactions.actions.actions
Regarding the last part of this package coordinate: it should be something like `endbug`. Please notice what directories exist here: https://github.com/krzema12/github-actions-kotlin-dsl/tree/main/library/src/main/kotlin/it/krzeminski/githubactions/actions - they correspond to the owners of actions. This way I achieve namespacing, so that two actions named identically can coexist.

The same for two other classes.

2022-01-31 19:47 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/RefreshVersionsPR.kt
> +class RefreshVersionsPR : FunSpec({
This is a test specific to the use case of refreshVersions and while I understand why you created it - it probably helped you iterate over it to adopt the Kotlin DSL - I'd prefer not having it in the library... I hope you don't mind and understand. Going this direction, anyone may want to test their workflows in the library :smile: I recommend keeping this test on a separate branch for now, and given that I release the library pretty frequently, hopefully it will end up in some real-life repo so that we can link to it in the README of this library.

2022-01-31 19:47 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/AddAndCommitV8.kt
> +    /** The arguments for the `git add` command */
Documenting the arguments - that's a great idea, I thought of it as well! Will need to backfill for existing actions. There's some risk that they will get out of sync with the descriptions in [the action's manifest](https://github.com/EndBug/add-and-commit/blob/main/action.yml), but I guess the benefit outweighs the risk, and it can be automated to keep these in sync/validate.

2022-01-31 19:50 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/actions/actions/AddAndCommitV8Test.kt
> +    it("renders with add") {
Recently when adding new wrappers, I took a more lightweight approach to unit-testing them: having two basic cases:
* `renders with defaults`
* `renders with all parameters`
See e.g. [here](https://github.com/krzema12/github-actions-kotlin-dsl/blob/main/library/src/test/kotlin/it/krzeminski/githubactions/actions/gradleupdate/UpdateGradleWrapperActionV1Test.kt). If some parameter is not a simple string or bool because it has its own type, then an extra test case is fine.

Why: it makes the tests way faster to write, and shorter and easier to read, while pretty much maintaining the precision of the tests.

2022-02-01 14:41 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/PullRequestV2.kt
> +) : Action("repo-sync", "pull-request", "v2.6.1") {
How do I specify a newer version as a user?

2022-02-01 14:41 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/AddAndCommitV8.kt
> +@Suppress("ConstructorParameterNaming")
Done

2022-02-01 14:41 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/AddAndCommitV8.kt
> +package it.krzeminski.githubactions.actions.actions
Done

2022-02-01 14:42 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/AddAndCommitV8.kt
> +    /** The arguments for the `git add` command */
I removed it

2022-02-01 14:42 UTC, jmfayard commented on library/src/test/kotlin/it/krzeminski/githubactions/actions/actions/AddAndCommitV8Test.kt
> +    it("renders with add") {
Done

2022-02-01 19:01 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/PullRequestV2.kt
> +) : Action("repo-sync", "pull-request", "v2.6.1") {
If a given action wrapper is tied to some major version, e.g. v2 here, I assume that GitHub will use the newest version of a given major version, according to [semver](https://semver.org/). If you need e.g. v3, we either need to add another wrapper class in this library (`PullRequestV3`), or you can create it locally in your project. Just changing the version from v2 to v3 in theory won't be enough if the action uses semver because it means a breaking change in the API. Does it make sense?

2022-02-01 19:19 UTC, krzema12 requested changes

2022-02-01 19:19 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/CreateBranchV210.kt
> +data class CreateBranchV210(
```suggestion
data class CreateBranchV2(
```

2022-02-01 19:19 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/CreateBranchV210.kt
> +package it.krzeminski.githubactions.actions.actions
```suggestion
package it.krzeminski.githubactions.actions.peterjgrainger
```

2022-02-01 19:19 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/endbug/AddAndCommitV8.kt
> +    val defaultAuthor: String? = null,
This argument can be nicely modeled as an enum or sealed class, to bring more type-safety and move what's written in the documentation to the type system. I do my best to not stay solely in the "string, int, bool" world :smile:  Please see what I did e.g. for Java distribution: https://github.com/krzema12/github-actions-kotlin-dsl/blob/dde8cd852e156383ef6e341b94fec929ed3244c8/library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/SetupJavaV2.kt#L41-L50

It's a sealed class, not an enum, to allow specifying custom value (`Custom`) in case this library lags with adding new options.

I think this trick can be applied here to `defaultAuthor`, `pathspecErrorHandling`, maybe also in other actions.

2022-02-01 19:19 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/reposync/PullRequestV2.kt
> +    val prReviewer: String? = null,
How about making it a `List<String>?`, for better type-safety and self-documentation? See what I did here: https://github.com/krzema12/github-actions-kotlin-dsl/blob/dde8cd852e156383ef6e341b94fec929ed3244c8/library/src/main/kotlin/it/krzeminski/githubactions/actions/gradle/WrapperValidationActionV1.kt#L8

It's then joined with a comma.
Similarly for `prAssignee` and `prLabel.

2022-02-01 19:19 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/endbug/AddAndCommitV8.kt
> +    val committerName: String? = null,
`commit` parameters is missing:
https://github.com/EndBug/add-and-commit/blob/0d80c341c41a60a76f2bce89ea93d9ec974eb63b/action.yml#L15-L17

BTW you can test if your wrapper has all parameters by using this tool: https://github.com/krzema12/github-actions-kotlin-dsl/blob/main/action-validation-tests/src/main/kotlin/Main.kt . I caught this missing parameter thanks to this. For now you need to manually replace whatever's assigned to `actionUnderTest`, it has to create the action with all parameters filled - I took it from the unit tests. Sometimes the branch in line 39 needs to be changed (`master` or `main`). One day I hope to have such tests in automatic manner.

2022-02-02 12:55 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/CreateBranchV210.kt
> +data class CreateBranchV210(
done

2022-02-02 12:55 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/CreateBranchV210.kt
> +package it.krzeminski.githubactions.actions.actions
done

2022-02-02 13:44 UTC, krzema12 requested changes

2022-02-02 13:44 UTC, krzema12 commented on library/src/test/kotlin/it/krzeminski/githubactions/actions/endbug/AddAndCommitV8Test.kt
> +            authorEmail = "mail@example.com",
Could you add `commit` argument also here?

2022-02-02 13:44 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/endbug/AddAndCommitV8.kt
> +sealed interface IDefaultActor : TypesSafeYaml
Could we avoid having `IDefaultActor` interface here? Does it have any advantages over the pattern with sealed class I showed [here](https://github.com/krzema12/github-actions-kotlin-dsl/blob/dde8cd852e156383ef6e341b94fec929ed3244c8/library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/SetupJavaV2.kt#L41-L50)?

2022-02-02 13:44 UTC, krzema12 commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/endbug/AddAndCommitV8.kt
> +enum class DefaultActor(override val yaml: String) : IDefaultActor {
Please put it all extra types inside the wrapper class, it works like a namespace. This way there can exist multiple wrappers that have the same name for such extra type and they can keep it for themselves independently. Example: [here](https://github.com/krzema12/github-actions-kotlin-dsl/blob/dde8cd852e156383ef6e341b94fec929ed3244c8/library/src/main/kotlin/it/krzeminski/githubactions/actions/actions/SetupJavaV2.kt) - the only top-level declaration is the wrapper class itself, and all the rest sits in the class.

I know these are non-obvious nuances, so I'm planning to document them here: https://github.com/krzema12/github-actions-kotlin-dsl/wiki/Creating-an-action-wrapper and in the future in the stand-alone docs.

2022-02-02 14:04 UTC, jmfayard commented on library/src/test/kotlin/it/krzeminski/githubactions/actions/endbug/AddAndCommitV8Test.kt
> +            authorEmail = "mail@example.com",
done

2022-02-02 14:05 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/endbug/AddAndCommitV8.kt
> +sealed interface IDefaultActor : TypesSafeYaml
it was a bit less verbose, but I was not a fan of IDefaultActor either
I changed it back

2022-02-02 14:05 UTC, jmfayard commented on library/src/main/kotlin/it/krzeminski/githubactions/actions/endbug/AddAndCommitV8.kt
> +enum class DefaultActor(override val yaml: String) : IDefaultActor {
done

2022-02-04 13:18 UTC, krzema12 commented
Please ensure that these wrappers work, after the changes around versions (`v2.1.0` -> `v2` may be an incorrect suggestion from my side).

2022-02-04 16:56 UTC, merged