Generate a Kotlin wrapper with Kotlin Poet
krzema12/github-actions-kotlin-dsl pull request #75
Opened 2022-02-08 11:52 UTC by jmfayard

I am able to generate the file `SetupnodeV2.kt` with KotlinPoet

2022-02-08 21:25 UTC, krzema12 requested changes
Great direction, I like it :)
To make a consistent change, let's make the SetupNodeV2 wrapper fully functional.

2022-02-08 21:25 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/KotlinPoet.kt
> +        .addCode("return TODO(%S)", "You need to implement toYamlArguments()")
This is a must-have to have MVP :)

2022-02-08 21:25 UTC, krzema12 commented on wrapper-generator/src/main/kotlin/Generation.kt
> +fun ActionCoords.generateWrapper(
If we're going the kotlinpoet way, this function is not needed right?

2022-02-08 21:25 UTC, krzema12 commented on wrapper-generator/src/test/kotlin/GenerationTest.kt
> +class GenerationTest : FunSpec({
Let's have some tests for the kotlinpoet approach.

2022-02-09 11:22 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/Generation.kt
> +fun ActionCoords.generateWrapper(
Removed

2022-02-09 11:22 UTC, jmfayard commented on wrapper-generator/src/main/kotlin/KotlinPoet.kt
> +        .addCode("return TODO(%S)", "You need to implement toYamlArguments()")
Done

2022-02-09 11:22 UTC, jmfayard commented on wrapper-generator/src/test/kotlin/GenerationTest.kt
> +class GenerationTest : FunSpec({
Done

2022-02-09 11:24 UTC, jmfayard commented
@krzema12 
- [The Wrapper now supporst Parameters of type boolean and integer](https://github.com/krzema12/github-actions-kotlin-dsl/pull/75/commits/df6ec8e3dccd33612cc09343e627283215cea874) - based on the default value of the parameter
- the function `toYamlArguments()` is now automatically generated
- the test class MyActionTest is now automatically generated

2022-02-09 14:11 UTC, jmfayard commented
@krzema12 I added a command to generate the wrapper from the command-line

`./gradlew :wrapper-generator:run --args https://github.com/peterjgrainger/action-create-branch/releases/tag/v2.1.0`

I'm now done feature-wise

2022-02-09 18:48 UTC, krzema12 commented
Please don't bother about the merge conflicts, I'm introducing these changes in smaller chunks and with slightly different approach, using you PR as inspiration/reference implementation. I'll mark you as author wherever necessary. Thanks for your effort! :tada:

2022-02-13 22:23 UTC, closed without merging